// Comprehensive Neural Knowledge Base Index for New Hyderi Nimco & Frozen
// Automatically Generated & Verified for 1,000+ Customer Query Variations
// Covers 54 Products, Karachi Areas, COD/Meezan/EasyPaisa, Cooking Tips, Expiry & Bulk Deals.

export const KNOWLEDGE_BASE_QA = [
  {
    "category": "greeting",
    "patterns": [
      "salam",
      "assalam",
      "assalam o alaikum",
      "assalamu alaikum",
      "asalam",
      "aoa",
      "hi",
      "hello",
      "hey",
      "hyderi nimco",
      "adaab",
      "salam bhai",
      "assalam alaikum",
      "salam u alaikum",
      "salam janab",
      "salam sahab",
      "slam",
      "aslamoalekom",
      "aslam alikum",
      "kya haal hai",
      "kese ho",
      "kaise ho bhai",
      "sab theek",
      "sub theek",
      "aur bhai"
    ],
    "answer": "Walaikum Assalam bhai! New Hyderi Nimco & Frozen Foods (Since 1970) me welcome! 🥟✨\n\nHamari taraf se aapki kya khidmat kar sakte hain? Aapko kya chahiye?\n\nAap mujh se:\n• 🥟 *Menu & Rates:* Samosay, Rolls, Kababs, Pizzas ya Nimco ke rates\n• 🛒 *Order:* Direct home delivery order book karwana\n• 💵 *Payment:* Cash on Delivery (COD) ya EasyPaisa / Meezan Bank\n• 🎁 *Party & Dawat:* Bulk discount aur guests estimation\n• 🛵 *Free Delivery:* Rs. 5,000 par poore Karachi me Free Delivery\n\njo bhi chahein pooch sakte hain! Bataiye hum aapki kaise madad kar sakte hain ya aapko kya chahiye?"
  },
  {
    "category": "owner_info",
    "patterns": [
      "arsalan",
      "arsalan bhai",
      "arsalan bhai ki shop hai",
      "arsalan ki shop",
      "arsalan bhai hain",
      "arsalan sahib",
      "owner kon hai",
      "dukandar kon hai",
      "shop owner",
      "arsalan arsalan",
      "arsalan bhai ki dukan"
    ],
    "answer": "Ji haan bilkul! 👑 Ye Arsalan Bhai ki hi official shop 'New Hyderi Nimco & Frozen Foods (Since 1970)' hai 🥟✨\n\n📍 *Address:* Shop # 20, 21, Burhani Bagh, Block-E, Hydri, North Nazimabad, Karachi.\n📞 *Helpline / WhatsApp:* 0336-2438422 / 0325-2747343\n💳 *EasyPaisa / Raast Title:* Arsalan Arsalan (0336-2438422)\n🏦 *Meezan Bank Title:* ARSALAN (01870100080247)\n\nArsalan Bhai ke direct supervision me hamare 100% zabiha halal, taaza aur hygenic frozen items daily tayar hote hain. Aapko kon se items (Samosa, Roll, Kabab, Nimco) chahiye? Mai abhi order book kar deta hoon!"
  },
  {
    "category": "muneeb_info",
    "patterns": [
      "muneeb",
      "muneeb kon hai",
      "muneeb bhai",
      "muneeb kon h",
      "who is muneeb"
    ],
    "answer": "Muneeb HTM ka Co-Founder hai."
  },
  {
    "category": "zaid_info",
    "patterns": [
      "zaid",
      "zaid kon hai",
      "zaid bhai",
      "zaid kon h",
      "who is zaid"
    ],
    "answer": "Zaid Al Balochi king hai."
  },
  {
    "category": "wahab_info",
    "patterns": [
      "wahab",
      "wahab kon hai",
      "wahab bhai",
      "wahab kon h",
      "who is wahab"
    ],
    "answer": "Wahab gando bhrwa hai."
  },
  {
    "category": "hussain_info",
    "patterns": [
      "hussain",
      "hussain kon hai",
      "hussain bhai",
      "hussain kon h",
      "who is hussain"
    ],
    "answer": "Hussain zaid ka tatta geer hai."
  },
  {
    "category": "order",
    "patterns": [
      "order karna hai",
      "order kahan se karun",
      "order kaise dein",
      "order lene ka tareeqa",
      "order book karo",
      "order dena hai",
      "order place karna hai",
      "mangwana hai",
      "cheezein chahiye",
      "mujhe parcel chahiye",
      "order send karo",
      "order receive kaise hoga",
      "order process kya hai",
      "kharidna chahta hoon",
      "buy karna hai",
      "purchase kaise karun",
      "booking kahan hogi",
      "order kese place karein",
      "how to order",
      "place order",
      "want to buy",
      "order process",
      "cheez mangwani hai",
      "order likh lo",
      "mujhe order dena hai",
      "home delivery chahiye",
      "ghar mangwana hai",
      "parcel deliver kar do",
      "parcel bhejo",
      "saman chahiye",
      "booking kar do",
      "order book kar lein",
      "order note karo",
      "likh lo order"
    ],
    "answer": "Ji bilkul bhai, order abhi book kar letay hain! 🥟✨\n\nAap mujhe yahan WhatsApp par ye 3 cheezein bhej dein:\n1. *Items & Quantity:* Konsay items aur kitne packets chahiye? (e.g. 2 packet Chicken Samosa, 1 packet Shami Kabab)\n2. *Delivery Address:* Aapka Naam, Phone Number aur Karachi ka complete address.\n3. *Payment Choice:* Cash on Delivery (COD) par mangwana hai ya EasyPaisa / Meezan Bank se advance bhejenge?\n\n✨ *Free Delivery:* Rs. 5,000 ya is se baray order par poore Karachi me delivery bilkul FREE hai!\n🌐 Ya aap direct hamari website https://hyderinimco-frozen.com par ja kar bhi 1-click checkout kar sakte hain!"
  },
  {
    "category": "order_confirmation",
    "patterns": [
      "order confirm karo",
      "order confirm kaise hoga",
      "iska order confirm karo",
      "confirm my order",
      "order pakka karo",
      "mera order final karo",
      "order finalize karo",
      "order confirm karne ka tareeqa",
      "order kaise confirm hoga",
      "confirm order please",
      "pakka order hai",
      "order confirm karein",
      "haan confirm hai",
      "confirm kar dein",
      "final kar do",
      "mera order lock karo",
      "dispatch kar do"
    ],
    "answer": "Bhai order confirm karne ka bohot aasan tareeqa hai! 🥟✨\n\nBas mujhe yahan ye 3 cheezein likh kar bhej dein:\n• Konsay items aur kitne packets chahiye?\n• Aapka Naam, Phone Number aur Karachi Delivery Address\n• Payment: Cash on Delivery (COD) ya EasyPaisa (0336-2438422) / Meezan Bank (01870100080247)\n\nYe details aate hi aapka order kitchen me pack hone chala jayega aur dispatch alert mil jayega!"
  },
  {
    "category": "minimum_order",
    "patterns": [
      "minimum order kitna hai",
      "kam se kam kitna order kar sakte hain",
      "min order",
      "kam az kam order",
      "kya 1 packet mangwa sakte hain",
      "1 packet deliver hoga",
      "ek packet delivery",
      "chhota order",
      "minimum order limit kya hai",
      "single packet order",
      "sirf 1 packet milega",
      "aik packet de do",
      "kam se kam kitne packet",
      "minimum limit kya hai",
      "sirf ek dabba"
    ],
    "answer": "Bhai hamara koi strict minimum order limit nahi hai! Aap chahein to sirf *1 packet* bhi mangwa sakte hain.\n\n• Normal delivery fee sirf Rs. 150/- hoti hai.\n• Aur agar aapka order *Rs. 5,000* ya is se zyada ka banta hai to poore Karachi me delivery bilkul **FREE** hoti hai! 🥟🛵"
  },
  {
    "category": "payment_methods",
    "patterns": [
      "payment kese karo",
      "payment kaise karun",
      "payment methods kya hain",
      "paise kaise doon",
      "paise kaise bhejne hain",
      "payment ka kya tareeqa hai",
      "pay kaise karoon",
      "paise kab dene hain",
      "advance pay karna hai ya baad me",
      "payment options",
      "how to pay",
      "paise lene ka tareeqa",
      "payment kaise letay ho",
      "online payment hoti hai",
      "bank transfer hota hai",
      "paise transfer kaise karun"
    ],
    "answer": "💳 *Payment Ke 2 Bohot Aasan Tareeqay Hain:*\n\n1. 💵 *Cash on Delivery (COD):*\nPehle koi advance paise dene ki zaroorat nahi hai. Parcel milne par rider ko cash haath me ada kar dein.\n\n2. 📱 *Online Advance Payment:*\n• *EasyPaisa:* 0336-2438422 (Account Title: *Arsalan Arsalan*)\n• *Meezan Bank:* 01870100080247 (Account Title: *ARSALAN*)\n\nOnline bhej kar Transaction ID (TID) ya screenshot yahan bhej dein, order foran pack ho kar rider ko de diya jayega!"
  },
  {
    "category": "cod_inquiry",
    "patterns": [
      "cod hai",
      "cash on delivery hai",
      "cash on delivery available hai",
      "kya cod mil sakta hai",
      "rider ko paise de sakte hain",
      "saman milne par paise de sakte hain",
      "hath me cash",
      "haath me paise",
      "cash on dilevery",
      "cod option",
      "delivery par cash",
      "cash on delivery doge",
      "cod kar do",
      "ghar pohnchne par paise",
      "parcel dekh kar paise",
      "pehle saman baad me paise",
      "cod available hai"
    ],
    "answer": "Ji haan bilkul ۱۰۰٪! **Cash on Delivery (COD) hamare paas mukammal available hai!** 💵\n\nAapko pehle advance paise bhejne ki koi zaroorat nahi hai. Jab rider chilled cold box me frozen items aapke ghar pohnchayega, tab aap parcel check kar ke mouqay par rider ko cash ada kar sakte hain!"
  },
  {
    "category": "easypaisa_account",
    "patterns": [
      "easypaisa number do",
      "easypaisa account kya hai",
      "easypaisa account title",
      "easypaisa ka number",
      "easy paisa details",
      "shop owner ka easypaisa",
      "easypaisa account batao",
      "easypaisa details please",
      "easypaisa per bhej doon",
      "easypaisa karna hai",
      "easypaisa id",
      "owner easypaisa",
      "easypaisa account name"
    ],
    "answer": "📱 *Hyderi Nimco & Frozen - Official EasyPaisa Account:*\n\n• Mobile Account Number: **0336-2438422** (03362438422)\n• Account Title: **Arsalan Arsalan** (Shop Owner)\n\nPaise bhej kar TID (Transaction ID) ya screenshot yahan WhatsApp par share karein taake order foran verify ho kar dispatch ho jaye!"
  },
  {
    "category": "meezan_bank_account",
    "patterns": [
      "meezan bank account",
      "bank transfer details",
      "bank account number do",
      "bank details kya hain",
      "meezan account number",
      "meezan bank details",
      "bank account title",
      "iban number",
      "bank transfer",
      "online transfer details",
      "meezan me bhejun",
      "bank account kya hai",
      "raast id kya hai",
      "bank se payment"
    ],
    "answer": "🏦 *Hyderi Nimco & Frozen - Official Bank Account:*\n\n• Bank Name: **Meezan Bank Limited**\n• Account Title: **ARSALAN**\n• Account Number: **01870100080247**\n\nKisi bhi bank app ya Raast se direct transfer kar ke TID ya receipt yahan WhatsApp par share karein!"
  },
  {
    "category": "jazzcash_status",
    "patterns": [
      "jazzcash hai",
      "jazz cash number do",
      "jazzcash account",
      "jazz cash se pay kar sakte hain",
      "jazzcash se bhejun",
      "jazzcash accept karte ho",
      "jazzcash par paise bhejun",
      "jazzcash ka batao"
    ],
    "answer": "Bhai hamara JazzCash option filhal band hai. Aap payment ke liye:\n1. 💵 **Cash on Delivery (COD)**\n2. 📱 **EasyPaisa:** 0336-2438422 (Title: Arsalan Arsalan)\n3. 🏦 **Meezan Bank:** 01870100080247 (Title: ARSALAN)\n\nistemaal kar sakte hain!"
  },
  {
    "category": "delivery_timing",
    "patterns": [
      "delivery timing kya hai",
      "kitni der me aayega",
      "kab tak milega",
      "delivery kitne baje tak hoti hai",
      "aaj mil jayega",
      "same day delivery",
      "kitna time lagega",
      "delivery time",
      "kab pohnchega",
      "urgent delivery",
      "foran chahiye",
      "abhi chahiye",
      "rider kab aayega",
      "kitne ghante lagenge",
      "delivery kab shuru hoti hai",
      "raat me delivery hoti hai",
      "subah delivery milegi",
      "timing batao delivery ki"
    ],
    "answer": "🛵 *Delivery Timings & Speed:*\n\n• Rozana subah **10:00 AM se raat 11:00 PM** tak delivery active hoti hai.\n• **North Nazimabad & nearby areas:** Sirf 30 se 45 minute me delivery!\n• **Rest of Karachi:** Same-day temperature-controlled delivery rider dispatch hota hai.\n• Items temperature-controlled cold box me aate hain taake bilkul frozen aur fresh rahein!"
  },
  {
    "category": "delivery_charges",
    "patterns": [
      "delivery charges kitne hain",
      "delivery fee kya hai",
      "delivery kitne ki hai",
      "charges kitne lagenge",
      "delivery charges kya hain",
      "rider charges",
      "free delivery kitne par hai",
      "free delivery kab hogi",
      "free delivery ka rule",
      "delivery charge",
      "delivery charges kitna hoga",
      "rider kitne lega",
      "delivery free hai ya paise lagenge",
      "delivery charges batao"
    ],
    "answer": "🛵 *Delivery Charges & Free Delivery Offer:*\n\n• **FREE DELIVERY:** Agar aapka order **Rs. 5,000** ya is se zyada ka hai to poore Karachi me delivery bilkul **FREE** hai! 🎉\n• Rs. 5,000 se kam order par mamooli flat delivery fee sirf **Rs. 150/-** hoti hai."
  },
  {
    "category": "delivery_areas",
    "patterns": [
      "kahan kahan deliver karte ho",
      "delivery areas kya hain",
      "kya DHA me deliver hoga",
      "clifton me aayega",
      "gulshan me delivery hai",
      "johar me aate ho",
      "malir me delivery hai",
      "kya poore karachi me aate ho",
      "bahria town me delivery",
      "fb area me aayega",
      "nazimabad me deliver karte ho",
      "korangi me delivery",
      "sadar me aate ho",
      "pechs me deliver karoge",
      "bahadurabad me deliver",
      "tariq road par",
      "scheme 33 me"
    ],
    "answer": "📍 *100% Karachi Coverage:*\n\nJi haan bhai! Hum **poore Karachi me** chilled frozen delivery karte hain:\n• North Nazimabad, Nazimabad, Buffer Zone, FB Area\n• Gulshan-e-Iqbal, Gulistan-e-Johar, PECHS, Bahadurabad\n• DHA (Defence Phases 1-8), Clifton, Saddar, Cantt\n• Malir, Model Colony, Scheme 33, Korangi wagera.\n\nTamam parcel cold box me aate hain taake raste me bilkul pighlein nahi!"
  },
  {
    "category": "frying_instructions",
    "patterns": [
      "talne ka tareeqa",
      "fry kaise karein",
      "how to fry",
      "talte waqt phat to nahi jayega",
      "oil kitna garm ho",
      "aanch kitni rakhni hai",
      "crispy kaise banayein",
      "tail kaisa hona chahiye",
      "cooking instruction",
      "talne ka sahi tareeqa batao",
      "phat jata hai kya karun",
      "crispy nahi ban raha",
      "deep fry kaise karein",
      "oil temperature kya ho",
      "fry karne ka tareeqa",
      "fry karte waqt patti phat jati hai"
    ],
    "answer": "🔥 *Perfect Golden & Crispy Fry Karne Ka Behtareen Tareeqa:*\n\n1. ❌ **Defrost Mat Karein:** Samosay aur rolls freezer se nikal kar direct garm tail me dalein. Agar defrost kiya to patti naram par sakti hai aur phat sakti hai.\n2. 🌡️ **Tail Ka Temperature:** Tail ko darmiyani aanch (medium heat) par pehle se garm karein. Bohat tez tail me bahar se jal jayenge aur andar se kachay rahenge.\n3. ⏱️ **Frying Time:** Darmiyani aanch par 4 se 5 minute tak golden brown hone tak talein.\n4. 🥟 Nateeja: 100% crispy patti, zero oil absorption aur juicy chicken filling!"
  },
  {
    "category": "air_fryer_baking",
    "patterns": [
      "air fryer me ban sakta hai",
      "air fryer me bake karein",
      "air fryer timing",
      "oven me bake hoga",
      "oil free fry",
      "bina tail ke",
      "air fryer me kitna time lagega",
      "airfryer temperature",
      "airfryer me tal sakte hain",
      "air fry kaise karein",
      "bina oil ke pakana",
      "diet walon ke liye"
    ],
    "answer": "💨 *Air Fryer & Oven Instructions:*\n\nJi haan bilkul! Hamare tamam Samosay, Rolls, Nuggets aur Patties Air Fryer me behtareen bante hain:\n• **Temperature:** 180°C par pre-heat karein.\n• **Oil Brush:** Thora sa oil patti par brush kar lein taake golden shine aaye.\n• **Timing:** 8 se 10 minute tak bake karein (beech me 5 minute par palat dein).\nNateeja: 90% kam tail aur bilkul crispy crunch!"
  },
  {
    "category": "defrost_inquiry",
    "patterns": [
      "defrost karna chahiye",
      "defrost karna zaroori hai",
      "thaw karna hai",
      "pehle pighlayein",
      "freezer se nikal kar kab talein",
      "baraf pighlayein ya direct talein",
      "defrost karein ya nahi",
      "bahar nikal kar rakhna hai"
    ],
    "answer": "🚫 **Khabardar: Defrost Bilkul Mat Karein!**\n\nFrozen samosay aur rolls ko kabhi bhi defrost ya pighlane ke liye bahar mat chhorein. Freezer se nikalte hi seedha darmiyani garm tail me daal kar fry karein. Defrost karne se patti paani chhor deti hai aur fry karte waqt phat sakti hai."
  },
  {
    "category": "shelf_life",
    "patterns": [
      "freezer me kitne din chalenge",
      "kitna arsa rakh sakte hain",
      "expiry date kya hai",
      "shelf life kitni hai",
      "kharab to nahi honge",
      "kitne maheene chalte hain",
      "freezer storage",
      "bachi hui patti kahan rakhein",
      "store kaise karein",
      "kitni dair taaza rahenge",
      "expiry kab ki hai",
      "kitne time tak fresh rahenge"
    ],
    "answer": "❄️ *Storage & Shelf Life (Expiry):*\n\n• **Freezer Life:** Hamare tamam frozen items deep freezer me **۳ ماہ (3 Months)** tak bilkul taaza aur fresh rehte hain.\n• **Preservative Free:** Hamare items me koi harmful chemical nahi hota, natural blast freezing se taaza rehte hain.\n• **Storage Tip:** Zaroorat ke mutabiq pieces nikal kar baki packet ko air-tight ziplock me band kar ke wapas freezer me rakh dein.\n• **Nimco:** Room temperature par air-tight jar me 2 mahine tak crispy rehti hai!"
  },
  {
    "category": "halal_inquiry",
    "patterns": [
      "halal chicken hai",
      "halal meat",
      "kya ye halal hai",
      "zabiha halal hai",
      "meat kahan se aata hai",
      "chicken ki quality",
      "shariah compliant",
      "halal guarantee",
      "halal zabiha hai na",
      "gosht kaisa hai",
      "chicken fresh hota hai"
    ],
    "answer": "🕌 *100% Shariah-Compliant Zabiha Halal:*\n\nJi haan bhai, bilkul ۱۰۰٪! Hamara tamam chicken aur beef certified Shariah-compliant Zabiha Halal slaughterhouses se aata hai. Kisi qism ka machine-cut ya questionable meat hargiz istemaal nahi hota. Aap mutmain ho kar order karein!"
  },
  {
    "category": "kids_and_mild_spice",
    "patterns": [
      "bachon ke liye kya hai",
      "kam mirch wala kya hai",
      "kids friendly items",
      "mild items",
      "chilli kam kis me hai",
      "zyada mirch to nahi hai",
      "kids lunch box ke liye",
      "school lunch ke liye",
      "bachon ka snack",
      "school tiffin ke liye",
      "chotay bachon ke liye"
    ],
    "answer": "👶 *Bachon & Mild (Kam Mirch) Ke Liye Best Items:*\n\n• **Chicken Malai Boti Samosa / Roll:** Bohat creamy aur bilkul mild.\n• **Chicken Nuggets & Popcorn:** Kids absolute favorite school lunch box snack.\n• **Chicken Cheese Ball & Cheese Lolypop:** Cheesy aur tasty.\n• **Chicken Cheese Crispy One-Bite Samosa:** Rich cheese and chicken.\n• **Mini Pizza (Malai Boti):** Kids party hit!\n\nYe tamam items bilkul light masalay ke sath tayar kiye jate hain."
  },
  {
    "category": "spicy_traditional",
    "patterns": [
      "chatpata kya hai",
      "spicy items batao",
      "tez mirch wala",
      "masaledar samosa",
      "karara kya hai",
      "traditional samosa",
      "tez mirch",
      "spicy roll",
      "chilli samosa"
    ],
    "answer": "🌶️ *Chatpatay & Traditional Spicy Lovers Ke Liye:*\n\n• **Chicken Bar B Q Samosa / Roll:** Smokey BBQ spice.\n• **Qeema Samosa:** Traditional spicy beef mince.\n• **Chicken Chapli & Beef Chapli Kabab:** Authentic Peshawari spicy crunch.\n• **Chicken Mayo Garlic Roll:** Garlic & zesty chili.\n• **Hyderi Special Mix Nimco:** Chatpati aur crunchy!"
  },
  {
    "category": "party_general",
    "patterns": [
      "dawat hai",
      "party hai",
      "mehman aa rahe hain",
      "catering order",
      "mehmanon ke liye",
      "shaadi ka order",
      "birthday party",
      "iftar party",
      "khatam majlis",
      "mehmanon ka khana",
      "dawat ke liye kya loon",
      "party me kya rakhun",
      "get together hai",
      "dawat menu"
    ],
    "answer": "🎉 *Party & Dawat Orders - Hyderi Special Recommendation:*\n\nHar guest ke liye standard formula:\n• 2 One-Bite Samosay (Chicken ya Cheese Crispy)\n• 1 Spring Roll (Mayo Garlic / Malai Boti)\n• 1 Shami Kabab ya Cutless\n• Hyderi Mix Nimco (Chai aur table snacks ke liye)\n\n✨ **Special Offer:** Rs. 5,000 se baray dawat orders par poore Karachi me Chilled Delivery bilkul **FREE** hoti hai aur sath me complimentary Nimco gift pack milta hai! Bataiye kitne mehmanon ki dawat hai?"
  },
  {
    "category": "bulk_discount",
    "patterns": [
      "discount milega",
      "quantity me discount",
      "bulk discount",
      "wholesale rate",
      "concession milegi",
      "choot doge",
      "riyayat karo",
      "10 packet par discount",
      "rate kam karo",
      "bara order hai discount do",
      "zyada packet lene par discount",
      "wholesale rate kya hai",
      "discount ka batao"
    ],
    "answer": "🎁 *Bulk & Quantity Discount Offers:*\n\n1. **FREE Chilled Delivery:** Rs. 5,000 ya is se baray order par poore Karachi me delivery bilkul FREE hai!\n2. **10+ Packets Bulk Deal:** 10 ya us se zyada packets ke order par hum customized package discount aur sath me Hyderi Special Nimco ka complimentary gift pack dete hain!\n3. **Catering / Event Deals:** Dawat aur shaadi ke baray orders ke liye special concession di jati hai.\n\nAapko kitne packets chahiye? Mujhe list batayein, mai aapka best quote banata hoon!"
  },
  {
    "category": "shop_location",
    "patterns": [
      "shop kahan hai",
      "dukan kahan hai",
      "location batao",
      "address kya hai",
      "shop timing kya hai",
      "dukan khuli hai",
      "branch kahan hai",
      "north nazimabad me kahan ho",
      "hydri me address",
      "dukan par aa kar le sakta hoon",
      "google map location",
      "shop visit",
      "dukan ka pata",
      "kahan aana hoga"
    ],
    "answer": "📍 *New Hyderi Nimco & Frozen - Shop Location:*\n\n🏢 **Address:** Shop # 20, 21, Burhani Bagh, Block-E, Hydri, North Nazimabad, Karachi.\n📞 **Helpline:** 0336-2438422 | 0325-2747343 | 021-36625698\n🕒 **Timings:** 10:00 AM to 11:00 PM (Monday to Sunday Open)\n🌐 **Website:** https://hyderinimco-frozen.com\n\nAap dukan par direct visit kar ke bhi khareed sakte hain aur home delivery bhi mangwa sakte hain!"
  },
  {
    "category": "order_tracking",
    "patterns": [
      "mera order kahan pohncha",
      "order status batao",
      "rider nahi aaya",
      "order track karna hai",
      "der ho gai",
      "kitni der me aayega mera order",
      "order dispatch hua",
      "track order",
      "rider ka number do",
      "order late hai"
    ],
    "answer": "📦 *Live Order Tracking & Support:*\n\nApna **Order Ref Number (HYD-XXXX)** yahan likh kar bhej dein, ya website https://hyderinimco-frozen.com par 'Track Order' me daal kar live status dekh lein.\n\nAap hamari hotline **0336-2438422** / **0325-2747343** par bhi call kar sakte hain. Mai foran kitchen aur rider se update le kar aapko batata hoon!"
  },
  {
    "category": "product_samosa-1",
    "patterns": [
      "chicken vonton kitne ka hai",
      "chicken vonton ka rate",
      "chicken vonton price",
      "chicken vonton ki qeemat",
      "chicken vonton kitne pcs hote hain",
      "chicken vonton packet rate",
      "rate of chicken vonton",
      "price of chicken vonton",
      "cost of chicken vonton",
      "chicken vonton chahiye",
      "chicken vonton mil jayega",
      "kya chicken vonton available hai",
      "1 packet chicken vonton",
      "packet of chicken vonton",
      "chicken vonton ka batao",
      "chicken vonton ka packet",
      "chicken vonton ka kya hisab hai",
      "chicken vonton kitne rupay ka hai",
      "چکن وانٹون کا ریٹ",
      "چکن وانٹون کی قیمت",
      "چکن وانٹون چاہیے"
    ],
    "answer": "• *Chicken Vonton* (چکن وانٹون) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 240/- per packet\n📝 *Description:* Crispy fried wonton wrappers stuffed with seasoned minced chicken and herbs.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_samosa-2",
    "patterns": [
      "aaloo one bite samosa kitne ka hai",
      "aaloo one bite samosa ka rate",
      "aaloo one bite samosa price",
      "aaloo one bite samosa ki qeemat",
      "aaloo one bite samosa kitne pcs hote hain",
      "aaloo one bite samosa packet rate",
      "rate of aaloo one bite samosa",
      "price of aaloo one bite samosa",
      "cost of aaloo one bite samosa",
      "aaloo one bite samosa chahiye",
      "aaloo one bite samosa mil jayega",
      "kya aaloo one bite samosa available hai",
      "1 packet aaloo one bite samosa",
      "packet of aaloo one bite samosa",
      "aaloo one bite samosa ka batao",
      "aaloo one bite samosa ka packet",
      "aaloo one bite samosa ka kya hisab hai",
      "aaloo one bite samosa kitne rupay ka hai",
      "آلو ون بائٹ سموسہ کا ریٹ",
      "آلو ون بائٹ سموسہ کی قیمت",
      "آلو ون بائٹ سموسہ چاہیے",
      "aaloo 1 bite samosa rate",
      "aaloo 1 bite samosa kitne ka hai",
      "aaloo 1 bite samosa price"
    ],
    "answer": "• *Aaloo One Bite Samosa* (آلو ون بائٹ سموسہ) 🥟✨\n📦 *Packing:* 24 pcs\n💰 *Price:* Rs. 350/- per packet\n📝 *Description:* Mini bite-sized crispy samosas filled with authentic spiced potato.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_samosa-3",
    "patterns": [
      "chicken one bite samosa kitne ka hai",
      "chicken one bite samosa ka rate",
      "chicken one bite samosa price",
      "chicken one bite samosa ki qeemat",
      "chicken one bite samosa kitne pcs hote hain",
      "chicken one bite samosa packet rate",
      "rate of chicken one bite samosa",
      "price of chicken one bite samosa",
      "cost of chicken one bite samosa",
      "chicken one bite samosa chahiye",
      "chicken one bite samosa mil jayega",
      "kya chicken one bite samosa available hai",
      "1 packet chicken one bite samosa",
      "packet of chicken one bite samosa",
      "chicken one bite samosa ka batao",
      "chicken one bite samosa ka packet",
      "chicken one bite samosa ka kya hisab hai",
      "chicken one bite samosa kitne rupay ka hai",
      "چکن ون بائٹ سموسہ کا ریٹ",
      "چکن ون بائٹ سموسہ کی قیمت",
      "چکن ون بائٹ سموسہ چاہیے",
      "chicken 1 bite samosa rate",
      "chicken 1 bite samosa kitne ka hai",
      "chicken 1 bite samosa price"
    ],
    "answer": "• *Chicken One Bite Samosa* (چکن ون بائٹ سموسہ) 🥟✨\n📦 *Packing:* 24 pcs\n💰 *Price:* Rs. 400/- per packet\n📝 *Description:* Bite-sized golden pastry filled with juicy shredded chicken.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_samosa-4",
    "patterns": [
      "chicken cheese crispy one bite samosa kitne ka hai",
      "chicken cheese crispy one bite samosa ka rate",
      "chicken cheese crispy one bite samosa price",
      "chicken cheese crispy one bite samosa ki qeemat",
      "chicken cheese crispy one bite samosa kitne pcs hote hain",
      "chicken cheese crispy one bite samosa packet rate",
      "rate of chicken cheese crispy one bite samosa",
      "price of chicken cheese crispy one bite samosa",
      "cost of chicken cheese crispy one bite samosa",
      "chicken cheese crispy one bite samosa chahiye",
      "chicken cheese crispy one bite samosa mil jayega",
      "kya chicken cheese crispy one bite samosa available hai",
      "1 packet chicken cheese crispy one bite samosa",
      "packet of chicken cheese crispy one bite samosa",
      "chicken cheese crispy one bite samosa ka batao",
      "chicken cheese crispy one bite samosa ka packet",
      "chicken cheese crispy one bite samosa ka kya hisab hai",
      "chicken cheese crispy one bite samosa kitne rupay ka hai",
      "چکن چیز کرسپی ون بائٹ سموسہ کا ریٹ",
      "چکن چیز کرسپی ون بائٹ سموسہ کی قیمت",
      "چکن چیز کرسپی ون بائٹ سموسہ چاہیے",
      "chicken cheese crispy 1 bite samosa rate",
      "chicken cheese crispy 1 bite samosa kitne ka hai",
      "chicken cheese crispy 1 bite samosa price"
    ],
    "answer": "• *Chicken Cheese Crispy One Bite Samosa* (چکن چیز کرسپی ون بائٹ سموسہ) 🥟✨\n📦 *Packing:* 24 pcs\n💰 *Price:* Rs. 500/- per packet\n📝 *Description:* Burst of melted mozzarella cheese and chicken in mini samosas.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_samosa-5",
    "patterns": [
      "chicken cone samosa kitne ka hai",
      "chicken cone samosa ka rate",
      "chicken cone samosa price",
      "chicken cone samosa ki qeemat",
      "chicken cone samosa kitne pcs hote hain",
      "chicken cone samosa packet rate",
      "rate of chicken cone samosa",
      "price of chicken cone samosa",
      "cost of chicken cone samosa",
      "chicken cone samosa chahiye",
      "chicken cone samosa mil jayega",
      "kya chicken cone samosa available hai",
      "1 packet chicken cone samosa",
      "packet of chicken cone samosa",
      "chicken cone samosa ka batao",
      "chicken cone samosa ka packet",
      "chicken cone samosa ka kya hisab hai",
      "chicken cone samosa kitne rupay ka hai",
      "چکن کون سموسہ کا ریٹ",
      "چکن کون سموسہ کی قیمت",
      "چکن کون سموسہ چاہیے"
    ],
    "answer": "• *Chicken Cone Samosa* (چکن کون سموسہ) 🥟✨\n📦 *Packing:* 06 pcs\n💰 *Price:* Rs. 350/- per packet\n📝 *Description:* Unique crunchy cone-shaped pastry loaded with spicy chicken filling.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_samosa-6",
    "patterns": [
      "chicken malai boti samosa kitne ka hai",
      "chicken malai boti samosa ka rate",
      "chicken malai boti samosa price",
      "chicken malai boti samosa ki qeemat",
      "chicken malai boti samosa kitne pcs hote hain",
      "chicken malai boti samosa packet rate",
      "rate of chicken malai boti samosa",
      "price of chicken malai boti samosa",
      "cost of chicken malai boti samosa",
      "chicken malai boti samosa chahiye",
      "chicken malai boti samosa mil jayega",
      "kya chicken malai boti samosa available hai",
      "1 packet chicken malai boti samosa",
      "packet of chicken malai boti samosa",
      "chicken malai boti samosa ka batao",
      "chicken malai boti samosa ka packet",
      "chicken malai boti samosa ka kya hisab hai",
      "chicken malai boti samosa kitne rupay ka hai",
      "چکن ملائی بوٹی سموسہ کا ریٹ",
      "چکن ملائی بوٹی سموسہ کی قیمت",
      "چکن ملائی بوٹی سموسہ چاہیے"
    ],
    "answer": "• *Chicken Malai Boti Samosa* (چکن ملائی بوٹی سموسہ) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 500/- per packet\n📝 *Description:* Tender chicken cooked in rich cream and mild herbs in crispy wrapper.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_samosa-7",
    "patterns": [
      "chicken bar b q samosa kitne ka hai",
      "chicken bar b q samosa ka rate",
      "chicken bar b q samosa price",
      "chicken bar b q samosa ki qeemat",
      "chicken bar b q samosa kitne pcs hote hain",
      "chicken bar b q samosa packet rate",
      "rate of chicken bar b q samosa",
      "price of chicken bar b q samosa",
      "cost of chicken bar b q samosa",
      "chicken bar b q samosa chahiye",
      "chicken bar b q samosa mil jayega",
      "kya chicken bar b q samosa available hai",
      "1 packet chicken bar b q samosa",
      "packet of chicken bar b q samosa",
      "chicken bar b q samosa ka batao",
      "chicken bar b q samosa ka packet",
      "chicken bar b q samosa ka kya hisab hai",
      "chicken bar b q samosa kitne rupay ka hai",
      "چکن بار بی کیو سموسہ کا ریٹ",
      "چکن بار بی کیو سموسہ کی قیمت",
      "چکن بار بی کیو سموسہ چاہیے"
    ],
    "answer": "• *Chicken Bar B Q Samosa* (چکن بار بی کیو سموسہ) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 500/- per packet\n📝 *Description:* Authentic charcoal-smoked BBQ spiced chicken chunks samosa.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_samosa-8",
    "patterns": [
      "chicken pizza samosa kitne ka hai",
      "chicken pizza samosa ka rate",
      "chicken pizza samosa price",
      "chicken pizza samosa ki qeemat",
      "chicken pizza samosa kitne pcs hote hain",
      "chicken pizza samosa packet rate",
      "rate of chicken pizza samosa",
      "price of chicken pizza samosa",
      "cost of chicken pizza samosa",
      "chicken pizza samosa chahiye",
      "chicken pizza samosa mil jayega",
      "kya chicken pizza samosa available hai",
      "1 packet chicken pizza samosa",
      "packet of chicken pizza samosa",
      "chicken pizza samosa ka batao",
      "chicken pizza samosa ka packet",
      "chicken pizza samosa ka kya hisab hai",
      "chicken pizza samosa kitne rupay ka hai",
      "چکن پیزا سموسہ کا ریٹ",
      "چکن پیزا سموسہ کی قیمت",
      "چکن پیزا سموسہ چاہیے"
    ],
    "answer": "• *Chicken Pizza Samosa* (چکن پیزا سموسہ) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 550/- per packet\n📝 *Description:* Pizza sauce, mozzarella cheese, capsicum, olives and chicken.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_samosa-9",
    "patterns": [
      "chicken cheese crispy samosa kitne ka hai",
      "chicken cheese crispy samosa ka rate",
      "chicken cheese crispy samosa price",
      "chicken cheese crispy samosa ki qeemat",
      "chicken cheese crispy samosa kitne pcs hote hain",
      "chicken cheese crispy samosa packet rate",
      "rate of chicken cheese crispy samosa",
      "price of chicken cheese crispy samosa",
      "cost of chicken cheese crispy samosa",
      "chicken cheese crispy samosa chahiye",
      "chicken cheese crispy samosa mil jayega",
      "kya chicken cheese crispy samosa available hai",
      "1 packet chicken cheese crispy samosa",
      "packet of chicken cheese crispy samosa",
      "chicken cheese crispy samosa ka batao",
      "chicken cheese crispy samosa ka packet",
      "chicken cheese crispy samosa ka kya hisab hai",
      "chicken cheese crispy samosa kitne rupay ka hai",
      "چکن چیز کرسپی سموسہ کا ریٹ",
      "چکن چیز کرسپی سموسہ کی قیمت",
      "چکن چیز کرسپی سموسہ چاہیے"
    ],
    "answer": "• *Chicken Cheese Crispy Samosa* (چکن چیز کرسپی سموسہ) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 400/- per packet\n📝 *Description:* Cheese blend with shredded chicken in crunchy triangular crust.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_samosa-10",
    "patterns": [
      "chicken chinese samosa kitne ka hai",
      "chicken chinese samosa ka rate",
      "chicken chinese samosa price",
      "chicken chinese samosa ki qeemat",
      "chicken chinese samosa kitne pcs hote hain",
      "chicken chinese samosa packet rate",
      "rate of chicken chinese samosa",
      "price of chicken chinese samosa",
      "cost of chicken chinese samosa",
      "chicken chinese samosa chahiye",
      "chicken chinese samosa mil jayega",
      "kya chicken chinese samosa available hai",
      "1 packet chicken chinese samosa",
      "packet of chicken chinese samosa",
      "chicken chinese samosa ka batao",
      "chicken chinese samosa ka packet",
      "chicken chinese samosa ka kya hisab hai",
      "chicken chinese samosa kitne rupay ka hai",
      "چکن چائنیز سموسہ کا ریٹ",
      "چکن چائنیز سموسہ کی قیمت",
      "چکن چائنیز سموسہ چاہیے"
    ],
    "answer": "• *Chicken Chinese Samosa* (چکن چائنیز سموسہ) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 350/- per packet\n📝 *Description:* Stir-fried vegetables, soy sauce, black pepper and chicken.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_samosa-11",
    "patterns": [
      "qeema samosa kitne ka hai",
      "qeema samosa ka rate",
      "qeema samosa price",
      "qeema samosa ki qeemat",
      "qeema samosa kitne pcs hote hain",
      "qeema samosa packet rate",
      "rate of qeema samosa",
      "price of qeema samosa",
      "cost of qeema samosa",
      "qeema samosa chahiye",
      "qeema samosa mil jayega",
      "kya qeema samosa available hai",
      "1 packet qeema samosa",
      "packet of qeema samosa",
      "qeema samosa ka batao",
      "qeema samosa ka packet",
      "qeema samosa ka kya hisab hai",
      "qeema samosa kitne rupay ka hai",
      "قیمہ سموسہ کا ریٹ",
      "قیمہ سموسہ کی قیمت",
      "قیمہ سموسہ چاہیے"
    ],
    "answer": "• *Qeema Samosa* (قیمہ سموسہ) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 350/- per packet\n📝 *Description:* Finely minced beef seasoned with onion, mint and garam masala.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_samosa-12",
    "patterns": [
      "aaloo samosa kitne ka hai",
      "aaloo samosa ka rate",
      "aaloo samosa price",
      "aaloo samosa ki qeemat",
      "aaloo samosa kitne pcs hote hain",
      "aaloo samosa packet rate",
      "rate of aaloo samosa",
      "price of aaloo samosa",
      "cost of aaloo samosa",
      "aaloo samosa chahiye",
      "aaloo samosa mil jayega",
      "kya aaloo samosa available hai",
      "1 packet aaloo samosa",
      "packet of aaloo samosa",
      "aaloo samosa ka batao",
      "aaloo samosa ka packet",
      "aaloo samosa ka kya hisab hai",
      "aaloo samosa kitne rupay ka hai",
      "آلو سموسہ کا ریٹ",
      "آلو سموسہ کی قیمت",
      "آلو سموسہ چاہیے"
    ],
    "answer": "• *Aaloo Samosa* (آلو سموسہ) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 300/- per packet\n📝 *Description:* Classic potato samosa with whole coriander and cumin spices.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_samosa-13",
    "patterns": [
      "daal samosa kitne ka hai",
      "daal samosa ka rate",
      "daal samosa price",
      "daal samosa ki qeemat",
      "daal samosa kitne pcs hote hain",
      "daal samosa packet rate",
      "rate of daal samosa",
      "price of daal samosa",
      "cost of daal samosa",
      "daal samosa chahiye",
      "daal samosa mil jayega",
      "kya daal samosa available hai",
      "1 packet daal samosa",
      "packet of daal samosa",
      "daal samosa ka batao",
      "daal samosa ka packet",
      "daal samosa ka kya hisab hai",
      "daal samosa kitne rupay ka hai",
      "دال سموسہ کا ریٹ",
      "دال سموسہ کی قیمت",
      "دال سموسہ چاہیے"
    ],
    "answer": "• *Daal Samosa* (دال سموسہ) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 300/- per packet\n📝 *Description:* Spiced split yellow lentil filling in extra crunchy pastry.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_roll-1",
    "patterns": [
      "chicken one bite roll kitne ka hai",
      "chicken one bite roll ka rate",
      "chicken one bite roll price",
      "chicken one bite roll ki qeemat",
      "chicken one bite roll kitne pcs hote hain",
      "chicken one bite roll packet rate",
      "rate of chicken one bite roll",
      "price of chicken one bite roll",
      "cost of chicken one bite roll",
      "chicken one bite roll chahiye",
      "chicken one bite roll mil jayega",
      "kya chicken one bite roll available hai",
      "1 packet chicken one bite roll",
      "packet of chicken one bite roll",
      "chicken one bite roll ka batao",
      "chicken one bite roll ka packet",
      "chicken one bite roll ka kya hisab hai",
      "chicken one bite roll kitne rupay ka hai",
      "چکن ون بائٹ رول کا ریٹ",
      "چکن ون بائٹ رول کی قیمت",
      "چکن ون بائٹ رول چاہیے",
      "chicken 1 bite roll rate",
      "chicken 1 bite roll kitne ka hai",
      "chicken 1 bite roll price"
    ],
    "answer": "• *Chicken One Bite Roll* (چکن ون بائٹ رول) 🥟✨\n📦 *Packing:* 24 pcs\n💰 *Price:* Rs. 500/- per packet\n📝 *Description:* Crispy miniature spring rolls packed with seasoned chicken.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_roll-2",
    "patterns": [
      "chicken cheese crispy one bite roll kitne ka hai",
      "chicken cheese crispy one bite roll ka rate",
      "chicken cheese crispy one bite roll price",
      "chicken cheese crispy one bite roll ki qeemat",
      "chicken cheese crispy one bite roll kitne pcs hote hain",
      "chicken cheese crispy one bite roll packet rate",
      "rate of chicken cheese crispy one bite roll",
      "price of chicken cheese crispy one bite roll",
      "cost of chicken cheese crispy one bite roll",
      "chicken cheese crispy one bite roll chahiye",
      "chicken cheese crispy one bite roll mil jayega",
      "kya chicken cheese crispy one bite roll available hai",
      "1 packet chicken cheese crispy one bite roll",
      "packet of chicken cheese crispy one bite roll",
      "chicken cheese crispy one bite roll ka batao",
      "chicken cheese crispy one bite roll ka packet",
      "chicken cheese crispy one bite roll ka kya hisab hai",
      "chicken cheese crispy one bite roll kitne rupay ka hai",
      "چکن چیز کرسپی ون بائٹ رول کا ریٹ",
      "چکن چیز کرسپی ون بائٹ رول کی قیمت",
      "چکن چیز کرسپی ون بائٹ رول چاہیے",
      "chicken cheese crispy 1 bite roll rate",
      "chicken cheese crispy 1 bite roll kitne ka hai",
      "chicken cheese crispy 1 bite roll price"
    ],
    "answer": "• *Chicken Cheese Crispy One Bite Roll* (چکن چیز کرسپی ون بائٹ رول) 🥟✨\n📦 *Packing:* 24 pcs\n💰 *Price:* Rs. 550/- per packet\n📝 *Description:* Extra crunchy mini rolls with premium cheese and chicken.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_roll-3",
    "patterns": [
      "chicken bar b q roll kitne ka hai",
      "chicken bar b q roll ka rate",
      "chicken bar b q roll price",
      "chicken bar b q roll ki qeemat",
      "chicken bar b q roll kitne pcs hote hain",
      "chicken bar b q roll packet rate",
      "rate of chicken bar b q roll",
      "price of chicken bar b q roll",
      "cost of chicken bar b q roll",
      "chicken bar b q roll chahiye",
      "chicken bar b q roll mil jayega",
      "kya chicken bar b q roll available hai",
      "1 packet chicken bar b q roll",
      "packet of chicken bar b q roll",
      "chicken bar b q roll ka batao",
      "chicken bar b q roll ka packet",
      "chicken bar b q roll ka kya hisab hai",
      "chicken bar b q roll kitne rupay ka hai",
      "چکن بار بی کیو رول کا ریٹ",
      "چکن بار بی کیو رول کی قیمت",
      "چکن بار بی کیو رول چاہیے"
    ],
    "answer": "• *Chicken Bar B Q Roll* (چکن بار بی کیو رول) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 500/- per packet\n📝 *Description:* Smoky charcoal BBQ chicken wrapped in crisp pastry rolls.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_roll-4",
    "patterns": [
      "chicken malai boti roll kitne ka hai",
      "chicken malai boti roll ka rate",
      "chicken malai boti roll price",
      "chicken malai boti roll ki qeemat",
      "chicken malai boti roll kitne pcs hote hain",
      "chicken malai boti roll packet rate",
      "rate of chicken malai boti roll",
      "price of chicken malai boti roll",
      "cost of chicken malai boti roll",
      "chicken malai boti roll chahiye",
      "chicken malai boti roll mil jayega",
      "kya chicken malai boti roll available hai",
      "1 packet chicken malai boti roll",
      "packet of chicken malai boti roll",
      "chicken malai boti roll ka batao",
      "chicken malai boti roll ka packet",
      "chicken malai boti roll ka kya hisab hai",
      "chicken malai boti roll kitne rupay ka hai",
      "چکن ملائی بوٹی رول کا ریٹ",
      "چکن ملائی بوٹی رول کی قیمت",
      "چکن ملائی بوٹی رول چاہیے"
    ],
    "answer": "• *Chicken Malai Boti Roll* (چکن ملائی بوٹی رول) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 500/- per packet\n📝 *Description:* Rich creamy marinated chicken filling inside a golden crispy roll.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_roll-5",
    "patterns": [
      "chicken malai boti one bite roll kitne ka hai",
      "chicken malai boti one bite roll ka rate",
      "chicken malai boti one bite roll price",
      "chicken malai boti one bite roll ki qeemat",
      "chicken malai boti one bite roll kitne pcs hote hain",
      "chicken malai boti one bite roll packet rate",
      "rate of chicken malai boti one bite roll",
      "price of chicken malai boti one bite roll",
      "cost of chicken malai boti one bite roll",
      "chicken malai boti one bite roll chahiye",
      "chicken malai boti one bite roll mil jayega",
      "kya chicken malai boti one bite roll available hai",
      "1 packet chicken malai boti one bite roll",
      "packet of chicken malai boti one bite roll",
      "chicken malai boti one bite roll ka batao",
      "chicken malai boti one bite roll ka packet",
      "chicken malai boti one bite roll ka kya hisab hai",
      "chicken malai boti one bite roll kitne rupay ka hai",
      "چکن ملائی بوٹی ون بائٹ رول کا ریٹ",
      "چکن ملائی بوٹی ون بائٹ رول کی قیمت",
      "چکن ملائی بوٹی ون بائٹ رول چاہیے",
      "chicken malai boti 1 bite roll rate",
      "chicken malai boti 1 bite roll kitne ka hai",
      "chicken malai boti 1 bite roll price"
    ],
    "answer": "• *Chicken Malai Boti One Bite Roll* (چکن ملائی بوٹی ون بائٹ رول) 🥟✨\n📦 *Packing:* 24 pcs\n💰 *Price:* Rs. 500/- per packet\n📝 *Description:* Bite-sized creamy chicken malai boti rolls for tea time.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_roll-6",
    "patterns": [
      "chicken pizza roll kitne ka hai",
      "chicken pizza roll ka rate",
      "chicken pizza roll price",
      "chicken pizza roll ki qeemat",
      "chicken pizza roll kitne pcs hote hain",
      "chicken pizza roll packet rate",
      "rate of chicken pizza roll",
      "price of chicken pizza roll",
      "cost of chicken pizza roll",
      "chicken pizza roll chahiye",
      "chicken pizza roll mil jayega",
      "kya chicken pizza roll available hai",
      "1 packet chicken pizza roll",
      "packet of chicken pizza roll",
      "chicken pizza roll ka batao",
      "chicken pizza roll ka packet",
      "chicken pizza roll ka kya hisab hai",
      "chicken pizza roll kitne rupay ka hai",
      "چکن پیزا رول کا ریٹ",
      "چکن پیزا رول کی قیمت",
      "چکن پیزا رول چاہیے"
    ],
    "answer": "• *Chicken Pizza Roll* (چکن پیزا رول) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 550/- per packet\n📝 *Description:* Pizza-sauce, oregano, melted cheese, and capsicum in crispy roll.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_roll-7",
    "patterns": [
      "chicken mayo garlic roll kitne ka hai",
      "chicken mayo garlic roll ka rate",
      "chicken mayo garlic roll price",
      "chicken mayo garlic roll ki qeemat",
      "chicken mayo garlic roll kitne pcs hote hain",
      "chicken mayo garlic roll packet rate",
      "rate of chicken mayo garlic roll",
      "price of chicken mayo garlic roll",
      "cost of chicken mayo garlic roll",
      "chicken mayo garlic roll chahiye",
      "chicken mayo garlic roll mil jayega",
      "kya chicken mayo garlic roll available hai",
      "1 packet chicken mayo garlic roll",
      "packet of chicken mayo garlic roll",
      "chicken mayo garlic roll ka batao",
      "chicken mayo garlic roll ka packet",
      "chicken mayo garlic roll ka kya hisab hai",
      "chicken mayo garlic roll kitne rupay ka hai",
      "چکن مایو گارلک رول کا ریٹ",
      "چکن مایو گارلک رول کی قیمت",
      "چکن مایو گارلک رول چاہیے"
    ],
    "answer": "• *Chicken Mayo Garlic Roll* (چکن مایو گارلک رول) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 500/- per packet\n📝 *Description:* Creamy garlic mayonnaise tossed with tender chicken chunks.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_roll-8",
    "patterns": [
      "chicken cheese crispy roll kitne ka hai",
      "chicken cheese crispy roll ka rate",
      "chicken cheese crispy roll price",
      "chicken cheese crispy roll ki qeemat",
      "chicken cheese crispy roll kitne pcs hote hain",
      "chicken cheese crispy roll packet rate",
      "rate of chicken cheese crispy roll",
      "price of chicken cheese crispy roll",
      "cost of chicken cheese crispy roll",
      "chicken cheese crispy roll chahiye",
      "chicken cheese crispy roll mil jayega",
      "kya chicken cheese crispy roll available hai",
      "1 packet chicken cheese crispy roll",
      "packet of chicken cheese crispy roll",
      "chicken cheese crispy roll ka batao",
      "chicken cheese crispy roll ka packet",
      "chicken cheese crispy roll ka kya hisab hai",
      "chicken cheese crispy roll kitne rupay ka hai",
      "چکن چیز کرسپی رول کا ریٹ",
      "چکن چیز کرسپی رول کی قیمت",
      "چکن چیز کرسپی رول چاہیے"
    ],
    "answer": "• *Chicken Cheese Crispy Roll* (چکن چیز کرسپی رول) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 400/- per packet\n📝 *Description:* Golden crispy roll with melting mozzarella and chicken.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_roll-9",
    "patterns": [
      "chicken shahi roll kitne ka hai",
      "chicken shahi roll ka rate",
      "chicken shahi roll price",
      "chicken shahi roll ki qeemat",
      "chicken shahi roll kitne pcs hote hain",
      "chicken shahi roll packet rate",
      "rate of chicken shahi roll",
      "price of chicken shahi roll",
      "cost of chicken shahi roll",
      "chicken shahi roll chahiye",
      "chicken shahi roll mil jayega",
      "kya chicken shahi roll available hai",
      "1 packet chicken shahi roll",
      "packet of chicken shahi roll",
      "chicken shahi roll ka batao",
      "chicken shahi roll ka packet",
      "chicken shahi roll ka kya hisab hai",
      "chicken shahi roll kitne rupay ka hai",
      "چکن شاہی رول کا ریٹ",
      "چکن شاہی رول کی قیمت",
      "چکن شاہی رول چاہیے"
    ],
    "answer": "• *Chicken Shahi Roll* (چکن شاہی رول) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 350/- per packet\n📝 *Description:* Royal recipe with delicately spiced chicken and aromatics.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_roll-10",
    "patterns": [
      "chicken mint roll kitne ka hai",
      "chicken mint roll ka rate",
      "chicken mint roll price",
      "chicken mint roll ki qeemat",
      "chicken mint roll kitne pcs hote hain",
      "chicken mint roll packet rate",
      "rate of chicken mint roll",
      "price of chicken mint roll",
      "cost of chicken mint roll",
      "chicken mint roll chahiye",
      "chicken mint roll mil jayega",
      "kya chicken mint roll available hai",
      "1 packet chicken mint roll",
      "packet of chicken mint roll",
      "chicken mint roll ka batao",
      "chicken mint roll ka packet",
      "chicken mint roll ka kya hisab hai",
      "chicken mint roll kitne rupay ka hai",
      "چکن منٹ رول کا ریٹ",
      "چکن منٹ رول کی قیمت",
      "چکن منٹ رول چاہیے"
    ],
    "answer": "• *Chicken Mint Roll* (چکن منٹ رول) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 350/- per packet\n📝 *Description:* Fresh garden mint and green herb chicken filling inside roll.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_roll-11",
    "patterns": [
      "chicken chinese roll kitne ka hai",
      "chicken chinese roll ka rate",
      "chicken chinese roll price",
      "chicken chinese roll ki qeemat",
      "chicken chinese roll kitne pcs hote hain",
      "chicken chinese roll packet rate",
      "rate of chicken chinese roll",
      "price of chicken chinese roll",
      "cost of chicken chinese roll",
      "chicken chinese roll chahiye",
      "chicken chinese roll mil jayega",
      "kya chicken chinese roll available hai",
      "1 packet chicken chinese roll",
      "packet of chicken chinese roll",
      "chicken chinese roll ka batao",
      "chicken chinese roll ka packet",
      "chicken chinese roll ka kya hisab hai",
      "chicken chinese roll kitne rupay ka hai",
      "چکن چائنیز رول کا ریٹ",
      "چکن چائنیز رول کی قیمت",
      "چکن چائنیز رول چاہیے"
    ],
    "answer": "• *Chicken Chinese Roll* (چکن چائنیز رول) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 350/- per packet\n📝 *Description:* Shredded chicken and julienne vegetables with soy sauce.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_roll-12",
    "patterns": [
      "chicken bread roll kitne ka hai",
      "chicken bread roll ka rate",
      "chicken bread roll price",
      "chicken bread roll ki qeemat",
      "chicken bread roll kitne pcs hote hain",
      "chicken bread roll packet rate",
      "rate of chicken bread roll",
      "price of chicken bread roll",
      "cost of chicken bread roll",
      "chicken bread roll chahiye",
      "chicken bread roll mil jayega",
      "kya chicken bread roll available hai",
      "1 packet chicken bread roll",
      "packet of chicken bread roll",
      "chicken bread roll ka batao",
      "chicken bread roll ka packet",
      "chicken bread roll ka kya hisab hai",
      "chicken bread roll kitne rupay ka hai",
      "چکن بریڈ رول کا ریٹ",
      "چکن بریڈ رول کی قیمت",
      "چکن بریڈ رول چاہیے"
    ],
    "answer": "• *Chicken Bread Roll* (چکن بریڈ رول) 🥟✨\n📦 *Packing:* 06 pcs\n💰 *Price:* Rs. 300/- per packet\n📝 *Description:* Soft bread rolled around chicken coated in crispy crumbs.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_roll-13",
    "patterns": [
      "chicken chimmy changa kitne ka hai",
      "chicken chimmy changa ka rate",
      "chicken chimmy changa price",
      "chicken chimmy changa ki qeemat",
      "chicken chimmy changa kitne pcs hote hain",
      "chicken chimmy changa packet rate",
      "rate of chicken chimmy changa",
      "price of chicken chimmy changa",
      "cost of chicken chimmy changa",
      "chicken chimmy changa chahiye",
      "chicken chimmy changa mil jayega",
      "kya chicken chimmy changa available hai",
      "1 packet chicken chimmy changa",
      "packet of chicken chimmy changa",
      "chicken chimmy changa ka batao",
      "chicken chimmy changa ka packet",
      "chicken chimmy changa ka kya hisab hai",
      "chicken chimmy changa kitne rupay ka hai",
      "چکن چمی چانگا کا ریٹ",
      "چکن چمی چانگا کی قیمت",
      "چکن چمی چانگا چاہیے"
    ],
    "answer": "• *Chicken Chimmy Changa* (چکن چمی چانگا) 🥟✨\n📦 *Packing:* 06 pcs\n💰 *Price:* Rs. 350/- per packet\n📝 *Description:* Deep-fried stuffed pocket loaded with spicy chicken and salsa.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_kabab-1",
    "patterns": [
      "chicken shami kabab kitne ka hai",
      "chicken shami kabab ka rate",
      "chicken shami kabab price",
      "chicken shami kabab ki qeemat",
      "chicken shami kabab kitne pcs hote hain",
      "chicken shami kabab packet rate",
      "rate of chicken shami kabab",
      "price of chicken shami kabab",
      "cost of chicken shami kabab",
      "chicken shami kabab chahiye",
      "chicken shami kabab mil jayega",
      "kya chicken shami kabab available hai",
      "1 packet chicken shami kabab",
      "packet of chicken shami kabab",
      "chicken shami kabab ka batao",
      "chicken shami kabab ka packet",
      "chicken shami kabab ka kya hisab hai",
      "chicken shami kabab kitne rupay ka hai",
      "چکن شامی کباب کا ریٹ",
      "چکن شامی کباب کی قیمت",
      "چکن شامی کباب چاہیے"
    ],
    "answer": "• *Chicken Shami Kabab* (چکن شامی کباب) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 600/- per packet\n📝 *Description:* Chicken and split yellow gram patties with fragrant spices.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_kabab-2",
    "patterns": [
      "beef shami kabab kitne ka hai",
      "beef shami kabab ka rate",
      "beef shami kabab price",
      "beef shami kabab ki qeemat",
      "beef shami kabab kitne pcs hote hain",
      "beef shami kabab packet rate",
      "rate of beef shami kabab",
      "price of beef shami kabab",
      "cost of beef shami kabab",
      "beef shami kabab chahiye",
      "beef shami kabab mil jayega",
      "kya beef shami kabab available hai",
      "1 packet beef shami kabab",
      "packet of beef shami kabab",
      "beef shami kabab ka batao",
      "beef shami kabab ka packet",
      "beef shami kabab ka kya hisab hai",
      "beef shami kabab kitne rupay ka hai",
      "بیف شامی کباب کا ریٹ",
      "بیف شامی کباب کی قیمت",
      "بیف شامی کباب چاہیے"
    ],
    "answer": "• *Beef Shami Kabab* (بیف شامی کباب) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 600/- per packet\n📝 *Description:* Traditional Karachi beef shami kababs with tender shredded beef.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_kabab-3",
    "patterns": [
      "chicken seekh kabab kitne ka hai",
      "chicken seekh kabab ka rate",
      "chicken seekh kabab price",
      "chicken seekh kabab ki qeemat",
      "chicken seekh kabab kitne pcs hote hain",
      "chicken seekh kabab packet rate",
      "rate of chicken seekh kabab",
      "price of chicken seekh kabab",
      "cost of chicken seekh kabab",
      "chicken seekh kabab chahiye",
      "chicken seekh kabab mil jayega",
      "kya chicken seekh kabab available hai",
      "1 packet chicken seekh kabab",
      "packet of chicken seekh kabab",
      "chicken seekh kabab ka batao",
      "chicken seekh kabab ka packet",
      "chicken seekh kabab ka kya hisab hai",
      "chicken seekh kabab kitne rupay ka hai",
      "چکن سیخ کباب کا ریٹ",
      "چکن سیخ کباب کی قیمت",
      "چکن سیخ کباب چاہیے"
    ],
    "answer": "• *Chicken Seekh Kabab* (چکن سیخ کباب) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 650/- per packet\n📝 *Description:* Minced chicken seasoned with coriander, cumin and BBQ smoke.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_kabab-4",
    "patterns": [
      "chicken chapli kabab kitne ka hai",
      "chicken chapli kabab ka rate",
      "chicken chapli kabab price",
      "chicken chapli kabab ki qeemat",
      "chicken chapli kabab kitne pcs hote hain",
      "chicken chapli kabab packet rate",
      "rate of chicken chapli kabab",
      "price of chicken chapli kabab",
      "cost of chicken chapli kabab",
      "chicken chapli kabab chahiye",
      "chicken chapli kabab mil jayega",
      "kya chicken chapli kabab available hai",
      "1 packet chicken chapli kabab",
      "packet of chicken chapli kabab",
      "chicken chapli kabab ka batao",
      "chicken chapli kabab ka packet",
      "chicken chapli kabab ka kya hisab hai",
      "chicken chapli kabab kitne rupay ka hai",
      "چکن چپلی کباب کا ریٹ",
      "چکن چپلی کباب کی قیمت",
      "چکن چپلی کباب چاہیے"
    ],
    "answer": "• *Chicken Chapli Kabab* (چکن چپلی کباب) 🥟✨\n📦 *Packing:* 06 pcs\n💰 *Price:* Rs. 500/- per packet\n📝 *Description:* Peshawari style chicken patty with crushed pomegranate and tomato.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_kabab-5",
    "patterns": [
      "beef chapli kabab kitne ka hai",
      "beef chapli kabab ka rate",
      "beef chapli kabab price",
      "beef chapli kabab ki qeemat",
      "beef chapli kabab kitne pcs hote hain",
      "beef chapli kabab packet rate",
      "rate of beef chapli kabab",
      "price of beef chapli kabab",
      "cost of beef chapli kabab",
      "beef chapli kabab chahiye",
      "beef chapli kabab mil jayega",
      "kya beef chapli kabab available hai",
      "1 packet beef chapli kabab",
      "packet of beef chapli kabab",
      "beef chapli kabab ka batao",
      "beef chapli kabab ka packet",
      "beef chapli kabab ka kya hisab hai",
      "beef chapli kabab kitne rupay ka hai",
      "بیف چپلی کباب کا ریٹ",
      "بیف چپلی کباب کی قیمت",
      "بیف چپلی کباب چاہیے"
    ],
    "answer": "• *Beef Chapli Kabab* (بیف چپلی کباب) 🥟✨\n📦 *Packing:* 06 pcs\n💰 *Price:* Rs. 500/- per packet\n📝 *Description:* Traditional spiced beef patty infused with chili flakes and mint.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_kabab-6",
    "patterns": [
      "chicken burger patty kitne ka hai",
      "chicken burger patty ka rate",
      "chicken burger patty price",
      "chicken burger patty ki qeemat",
      "chicken burger patty kitne pcs hote hain",
      "chicken burger patty packet rate",
      "rate of chicken burger patty",
      "price of chicken burger patty",
      "cost of chicken burger patty",
      "chicken burger patty chahiye",
      "chicken burger patty mil jayega",
      "kya chicken burger patty available hai",
      "1 packet chicken burger patty",
      "packet of chicken burger patty",
      "chicken burger patty ka batao",
      "chicken burger patty ka packet",
      "chicken burger patty ka kya hisab hai",
      "chicken burger patty kitne rupay ka hai",
      "چکن برگر پیٹی کا ریٹ",
      "چکن برگر پیٹی کی قیمت",
      "چکن برگر پیٹی چاہیے"
    ],
    "answer": "• *Chicken Burger Patty* (چکن برگر پیٹی) 🥟✨\n📦 *Packing:* 06 pcs\n💰 *Price:* Rs. 400/- per packet\n📝 *Description:* Juicy chicken burger patties ready for homemade burgers.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_kabab-7",
    "patterns": [
      "chicken cutless kitne ka hai",
      "chicken cutless ka rate",
      "chicken cutless price",
      "chicken cutless ki qeemat",
      "chicken cutless kitne pcs hote hain",
      "chicken cutless packet rate",
      "rate of chicken cutless",
      "price of chicken cutless",
      "cost of chicken cutless",
      "chicken cutless chahiye",
      "chicken cutless mil jayega",
      "kya chicken cutless available hai",
      "1 packet chicken cutless",
      "packet of chicken cutless",
      "chicken cutless ka batao",
      "chicken cutless ka packet",
      "chicken cutless ka kya hisab hai",
      "chicken cutless kitne rupay ka hai",
      "چکن کٹلس کا ریٹ",
      "چکن کٹلس کی قیمت",
      "چکن کٹلس چاہیے"
    ],
    "answer": "• *Chicken Cutless* (چکن کٹلس) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 500/- per packet\n📝 *Description:* Crumb coated mashed potato and chicken patties with green chilies.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_kabab-8",
    "patterns": [
      "chicken stick kitne ka hai",
      "chicken stick ka rate",
      "chicken stick price",
      "chicken stick ki qeemat",
      "chicken stick kitne pcs hote hain",
      "chicken stick packet rate",
      "rate of chicken stick",
      "price of chicken stick",
      "cost of chicken stick",
      "chicken stick chahiye",
      "chicken stick mil jayega",
      "kya chicken stick available hai",
      "1 packet chicken stick",
      "packet of chicken stick",
      "chicken stick ka batao",
      "chicken stick ka packet",
      "chicken stick ka kya hisab hai",
      "chicken stick kitne rupay ka hai",
      "چکن اسٹک کا ریٹ",
      "چکن اسٹک کی قیمت",
      "چکن اسٹک چاہیے"
    ],
    "answer": "• *Chicken Stick* (چکن اسٹک) 🥟✨\n📦 *Packing:* 06 pcs\n💰 *Price:* Rs. 550/- per packet\n📝 *Description:* Marinated juicy chicken chunks on skewers ready to fry.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_kabab-9",
    "patterns": [
      "chicken kofta kitne ka hai",
      "chicken kofta ka rate",
      "chicken kofta price",
      "chicken kofta ki qeemat",
      "chicken kofta kitne pcs hote hain",
      "chicken kofta packet rate",
      "rate of chicken kofta",
      "price of chicken kofta",
      "cost of chicken kofta",
      "chicken kofta chahiye",
      "chicken kofta mil jayega",
      "kya chicken kofta available hai",
      "1 packet chicken kofta",
      "packet of chicken kofta",
      "chicken kofta ka batao",
      "chicken kofta ka packet",
      "chicken kofta ka kya hisab hai",
      "chicken kofta kitne rupay ka hai",
      "چکن کوفتہ کا ریٹ",
      "چکن کوفتہ کی قیمت",
      "چکن کوفتہ چاہیے"
    ],
    "answer": "• *Chicken Kofta* (چکن کوفتہ) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 500/- per packet\n📝 *Description:* Succulent chicken meatballs blended with aromatic herbs.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_kabab-10",
    "patterns": [
      "chicken momos (steamed) kitne ka hai",
      "chicken momos (steamed) ka rate",
      "chicken momos (steamed) price",
      "chicken momos (steamed) ki qeemat",
      "chicken momos (steamed) kitne pcs hote hain",
      "chicken momos (steamed) packet rate",
      "rate of chicken momos (steamed)",
      "price of chicken momos (steamed)",
      "cost of chicken momos (steamed)",
      "chicken momos (steamed) chahiye",
      "chicken momos (steamed) mil jayega",
      "kya chicken momos (steamed) available hai",
      "1 packet chicken momos (steamed)",
      "packet of chicken momos (steamed)",
      "chicken momos (steamed) ka batao",
      "chicken momos (steamed) ka packet",
      "chicken momos (steamed) ka kya hisab hai",
      "chicken momos (steamed) kitne rupay ka hai",
      "چکن موموز (اسٹیمڈ) کا ریٹ",
      "چکن موموز (اسٹیمڈ) کی قیمت",
      "چکن موموز (اسٹیمڈ) چاہیے"
    ],
    "answer": "• *Chicken Momos (Steamed)* (چکن موموز (اسٹیمڈ)) 🥟✨\n📦 *Packing:* 10 pcs\n💰 *Price:* Rs. 400/- per packet\n📝 *Description:* Delicate steamed dumplings with minced chicken and ginger.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_kabab-11",
    "patterns": [
      "chicken momos (fried) kitne ka hai",
      "chicken momos (fried) ka rate",
      "chicken momos (fried) price",
      "chicken momos (fried) ki qeemat",
      "chicken momos (fried) kitne pcs hote hain",
      "chicken momos (fried) packet rate",
      "rate of chicken momos (fried)",
      "price of chicken momos (fried)",
      "cost of chicken momos (fried)",
      "chicken momos (fried) chahiye",
      "chicken momos (fried) mil jayega",
      "kya chicken momos (fried) available hai",
      "1 packet chicken momos (fried)",
      "packet of chicken momos (fried)",
      "chicken momos (fried) ka batao",
      "chicken momos (fried) ka packet",
      "chicken momos (fried) ka kya hisab hai",
      "chicken momos (fried) kitne rupay ka hai",
      "چکن موموز (فرائیڈ) کا ریٹ",
      "چکن موموز (فرائیڈ) کی قیمت",
      "چکن موموز (فرائیڈ) چاہیے"
    ],
    "answer": "• *Chicken Momos (Fried)* (چکن موموز (فرائیڈ)) 🥟✨\n📦 *Packing:* 08 pcs\n💰 *Price:* Rs. 400/- per packet\n📝 *Description:* Golden pan-fried crunchy momos stuffed with chicken.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_pizza-1",
    "patterns": [
      "b.b.q mini pizza kitne ka hai",
      "b.b.q mini pizza ka rate",
      "b.b.q mini pizza price",
      "b.b.q mini pizza ki qeemat",
      "b.b.q mini pizza kitne pcs hote hain",
      "b.b.q mini pizza packet rate",
      "rate of b.b.q mini pizza",
      "price of b.b.q mini pizza",
      "cost of b.b.q mini pizza",
      "b.b.q mini pizza chahiye",
      "b.b.q mini pizza mil jayega",
      "kya b.b.q mini pizza available hai",
      "1 packet b.b.q mini pizza",
      "packet of b.b.q mini pizza",
      "b.b.q mini pizza ka batao",
      "b.b.q mini pizza ka packet",
      "b.b.q mini pizza ka kya hisab hai",
      "b.b.q mini pizza kitne rupay ka hai",
      "بی بی کیو منی پیزا کا ریٹ",
      "بی بی کیو منی پیزا کی قیمت",
      "بی بی کیو منی پیزا چاہیے"
    ],
    "answer": "• *B.B.Q Mini Pizza* (بی بی کیو منی پیزا) 🥟✨\n📦 *Packing:* 06 pcs\n💰 *Price:* Rs. 450/- per packet\n📝 *Description:* Fluffy pizza dough with BBQ chicken, sauce and mozzarella cheese.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_pizza-2",
    "patterns": [
      "malai boti mini pizza kitne ka hai",
      "malai boti mini pizza ka rate",
      "malai boti mini pizza price",
      "malai boti mini pizza ki qeemat",
      "malai boti mini pizza kitne pcs hote hain",
      "malai boti mini pizza packet rate",
      "rate of malai boti mini pizza",
      "price of malai boti mini pizza",
      "cost of malai boti mini pizza",
      "malai boti mini pizza chahiye",
      "malai boti mini pizza mil jayega",
      "kya malai boti mini pizza available hai",
      "1 packet malai boti mini pizza",
      "packet of malai boti mini pizza",
      "malai boti mini pizza ka batao",
      "malai boti mini pizza ka packet",
      "malai boti mini pizza ka kya hisab hai",
      "malai boti mini pizza kitne rupay ka hai",
      "ملائی بوٹی منی پیزا کا ریٹ",
      "ملائی بوٹی منی پیزا کی قیمت",
      "ملائی بوٹی منی پیزا چاہیے"
    ],
    "answer": "• *Malai Boti Mini Pizza* (ملائی بوٹی منی پیزا) 🥟✨\n📦 *Packing:* 06 pcs\n💰 *Price:* Rs. 500/- per packet\n📝 *Description:* Creamy malai chicken boti topping with rich melted cheese.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_special-1",
    "patterns": [
      "hot shot kitne ka hai",
      "hot shot ka rate",
      "hot shot price",
      "hot shot ki qeemat",
      "hot shot kitne pcs hote hain",
      "hot shot packet rate",
      "rate of hot shot",
      "price of hot shot",
      "cost of hot shot",
      "hot shot chahiye",
      "hot shot mil jayega",
      "kya hot shot available hai",
      "1 packet hot shot",
      "packet of hot shot",
      "hot shot ka batao",
      "hot shot ka packet",
      "hot shot ka kya hisab hai",
      "hot shot kitne rupay ka hai",
      "ہاٹ شاٹس کا ریٹ",
      "ہاٹ شاٹس کی قیمت",
      "ہاٹ شاٹس چاہیے"
    ],
    "answer": "• *Hot Shot* (ہاٹ شاٹس) 🥟✨\n📦 *Packing:* 250gm - 06 pcs\n💰 *Price:* Rs. 450/- per packet\n📝 *Description:* Spicy battered bite-sized whole chicken breast chunks.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_special-2",
    "patterns": [
      "chicken nuggets big kitne ka hai",
      "chicken nuggets big ka rate",
      "chicken nuggets big price",
      "chicken nuggets big ki qeemat",
      "chicken nuggets big kitne pcs hote hain",
      "chicken nuggets big packet rate",
      "rate of chicken nuggets big",
      "price of chicken nuggets big",
      "cost of chicken nuggets big",
      "chicken nuggets big chahiye",
      "chicken nuggets big mil jayega",
      "kya chicken nuggets big available hai",
      "1 packet chicken nuggets big",
      "packet of chicken nuggets big",
      "chicken nuggets big ka batao",
      "chicken nuggets big ka packet",
      "chicken nuggets big ka kya hisab hai",
      "chicken nuggets big kitne rupay ka hai",
      "چکن نگٹس (بڑا پیک) کا ریٹ",
      "چکن نگٹس (بڑا پیک) کی قیمت",
      "چکن نگٹس (بڑا پیک) چاہیے"
    ],
    "answer": "• *Chicken Nuggets Big* (چکن نگٹس (بڑا پیک)) 🥟✨\n📦 *Packing:* 24 pcs\n💰 *Price:* Rs. 550/- per packet\n📝 *Description:* Crumbed pure chicken breast nuggets, family pack 24 pieces.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_special-3",
    "patterns": [
      "chicken nuggets small kitne ka hai",
      "chicken nuggets small ka rate",
      "chicken nuggets small price",
      "chicken nuggets small ki qeemat",
      "chicken nuggets small kitne pcs hote hain",
      "chicken nuggets small packet rate",
      "rate of chicken nuggets small",
      "price of chicken nuggets small",
      "cost of chicken nuggets small",
      "chicken nuggets small chahiye",
      "chicken nuggets small mil jayega",
      "kya chicken nuggets small available hai",
      "1 packet chicken nuggets small",
      "packet of chicken nuggets small",
      "chicken nuggets small ka batao",
      "chicken nuggets small ka packet",
      "chicken nuggets small ka kya hisab hai",
      "chicken nuggets small kitne rupay ka hai",
      "چکن نگٹس (چھوٹا پیک) کا ریٹ",
      "چکن نگٹس (چھوٹا پیک) کی قیمت",
      "چکن نگٹس (چھوٹا پیک) چاہیے"
    ],
    "answer": "• *Chicken Nuggets Small* (چکن نگٹس (چھوٹا پیک)) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 300/- per packet\n📝 *Description:* Crispy chicken nuggets 12 pieces small pack.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_special-4",
    "patterns": [
      "chicken cheese ball kitne ka hai",
      "chicken cheese ball ka rate",
      "chicken cheese ball price",
      "chicken cheese ball ki qeemat",
      "chicken cheese ball kitne pcs hote hain",
      "chicken cheese ball packet rate",
      "rate of chicken cheese ball",
      "price of chicken cheese ball",
      "cost of chicken cheese ball",
      "chicken cheese ball chahiye",
      "chicken cheese ball mil jayega",
      "kya chicken cheese ball available hai",
      "1 packet chicken cheese ball",
      "packet of chicken cheese ball",
      "chicken cheese ball ka batao",
      "chicken cheese ball ka packet",
      "chicken cheese ball ka kya hisab hai",
      "chicken cheese ball kitne rupay ka hai",
      "چکن چیز بولز کا ریٹ",
      "چکن چیز بولز کی قیمت",
      "چکن چیز بولز چاہیے"
    ],
    "answer": "• *Chicken Cheese Ball* (چکن چیز بولز) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 500/- per packet\n📝 *Description:* Crispy spheres packed with gooey cheese and chicken.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_special-5",
    "patterns": [
      "chicken cheese lolypop kitne ka hai",
      "chicken cheese lolypop ka rate",
      "chicken cheese lolypop price",
      "chicken cheese lolypop ki qeemat",
      "chicken cheese lolypop kitne pcs hote hain",
      "chicken cheese lolypop packet rate",
      "rate of chicken cheese lolypop",
      "price of chicken cheese lolypop",
      "cost of chicken cheese lolypop",
      "chicken cheese lolypop chahiye",
      "chicken cheese lolypop mil jayega",
      "kya chicken cheese lolypop available hai",
      "1 packet chicken cheese lolypop",
      "packet of chicken cheese lolypop",
      "chicken cheese lolypop ka batao",
      "chicken cheese lolypop ka packet",
      "chicken cheese lolypop ka kya hisab hai",
      "chicken cheese lolypop kitne rupay ka hai",
      "چکن چیز لولی پاپ کا ریٹ",
      "چکن چیز لولی پاپ کی قیمت",
      "چکن چیز لولی پاپ چاہیے"
    ],
    "answer": "• *Chicken Cheese Lolypop* (چکن چیز لولی پاپ) 🥟✨\n📦 *Packing:* 06 pcs\n💰 *Price:* Rs. 350/- per packet\n📝 *Description:* Chicken lollipop drumsticks stuffed with mozzarella cheese.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_special-6",
    "patterns": [
      "chicken donuts kitne ka hai",
      "chicken donuts ka rate",
      "chicken donuts price",
      "chicken donuts ki qeemat",
      "chicken donuts kitne pcs hote hain",
      "chicken donuts packet rate",
      "rate of chicken donuts",
      "price of chicken donuts",
      "cost of chicken donuts",
      "chicken donuts chahiye",
      "chicken donuts mil jayega",
      "kya chicken donuts available hai",
      "1 packet chicken donuts",
      "packet of chicken donuts",
      "chicken donuts ka batao",
      "chicken donuts ka packet",
      "chicken donuts ka kya hisab hai",
      "chicken donuts kitne rupay ka hai",
      "چکن ڈونٹس کا ریٹ",
      "چکن ڈونٹس کی قیمت",
      "چکن ڈونٹس چاہیے"
    ],
    "answer": "• *Chicken Donuts* (چکن ڈونٹس) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 500/- per packet\n📝 *Description:* Savory ring-shaped chicken patties coated in breadcrumbs.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_special-7",
    "patterns": [
      "chicken finger kitne ka hai",
      "chicken finger ka rate",
      "chicken finger price",
      "chicken finger ki qeemat",
      "chicken finger kitne pcs hote hain",
      "chicken finger packet rate",
      "rate of chicken finger",
      "price of chicken finger",
      "cost of chicken finger",
      "chicken finger chahiye",
      "chicken finger mil jayega",
      "kya chicken finger available hai",
      "1 packet chicken finger",
      "packet of chicken finger",
      "chicken finger ka batao",
      "chicken finger ka packet",
      "chicken finger ka kya hisab hai",
      "chicken finger kitne rupay ka hai",
      "چکن فنگرز کا ریٹ",
      "چکن فنگرز کی قیمت",
      "چکن فنگرز چاہیے"
    ],
    "answer": "• *Chicken Finger* (چکن فنگرز) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 400/- per packet\n📝 *Description:* Tender chicken strips in crunchy breading 12 pieces.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_special-8",
    "patterns": [
      "chicken popcorn kitne ka hai",
      "chicken popcorn ka rate",
      "chicken popcorn price",
      "chicken popcorn ki qeemat",
      "chicken popcorn kitne pcs hote hain",
      "chicken popcorn packet rate",
      "rate of chicken popcorn",
      "price of chicken popcorn",
      "cost of chicken popcorn",
      "chicken popcorn chahiye",
      "chicken popcorn mil jayega",
      "kya chicken popcorn available hai",
      "1 packet chicken popcorn",
      "packet of chicken popcorn",
      "chicken popcorn ka batao",
      "chicken popcorn ka packet",
      "chicken popcorn ka kya hisab hai",
      "chicken popcorn kitne rupay ka hai",
      "چکن پاپ کارن کا ریٹ",
      "چکن پاپ کارن کی قیمت",
      "چکن پاپ کارن چاہیے"
    ],
    "answer": "• *Chicken Popcorn* (چکن پاپ کارن) 🥟✨\n📦 *Packing:* 30 pcs\n💰 *Price:* Rs. 350/- per packet\n📝 *Description:* Bite-sized crunchy spiced popcorn chicken 30 pieces.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_special-9",
    "patterns": [
      "chicken chillos kitne ka hai",
      "chicken chillos ka rate",
      "chicken chillos price",
      "chicken chillos ki qeemat",
      "chicken chillos kitne pcs hote hain",
      "chicken chillos packet rate",
      "rate of chicken chillos",
      "price of chicken chillos",
      "cost of chicken chillos",
      "chicken chillos chahiye",
      "chicken chillos mil jayega",
      "kya chicken chillos available hai",
      "1 packet chicken chillos",
      "packet of chicken chillos",
      "chicken chillos ka batao",
      "chicken chillos ka packet",
      "chicken chillos ka kya hisab hai",
      "chicken chillos kitne rupay ka hai",
      "چکن چیلووز کا ریٹ",
      "چکن چیلووز کی قیمت",
      "چکن چیلووز چاہیے"
    ],
    "answer": "• *Chicken Chillos* (چکن چیلووز) 🥟✨\n📦 *Packing:* 06 pcs\n💰 *Price:* Rs. 350/- per packet\n📝 *Description:* Green chili and chicken stuffed crispy patties 6 pieces.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_special-10",
    "patterns": [
      "chicken pizza puff kitne ka hai",
      "chicken pizza puff ka rate",
      "chicken pizza puff price",
      "chicken pizza puff ki qeemat",
      "chicken pizza puff kitne pcs hote hain",
      "chicken pizza puff packet rate",
      "rate of chicken pizza puff",
      "price of chicken pizza puff",
      "cost of chicken pizza puff",
      "chicken pizza puff chahiye",
      "chicken pizza puff mil jayega",
      "kya chicken pizza puff available hai",
      "1 packet chicken pizza puff",
      "packet of chicken pizza puff",
      "chicken pizza puff ka batao",
      "chicken pizza puff ka packet",
      "chicken pizza puff ka kya hisab hai",
      "chicken pizza puff kitne rupay ka hai",
      "چکن پیزا پف کا ریٹ",
      "چکن پیزا پف کی قیمت",
      "چکن پیزا پف چاہیے"
    ],
    "answer": "• *Chicken Pizza Puff* (چکن پیزا پف) 🥟✨\n📦 *Packing:* 12 pcs\n💰 *Price:* Rs. 450/- per packet\n📝 *Description:* Flaky puff pastry stuffed with pizza sauce, cheese and chicken.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_special-11",
    "patterns": [
      "french fries kitne ka hai",
      "french fries ka rate",
      "french fries price",
      "french fries ki qeemat",
      "french fries kitne pcs hote hain",
      "french fries packet rate",
      "rate of french fries",
      "price of french fries",
      "cost of french fries",
      "french fries chahiye",
      "french fries mil jayega",
      "kya french fries available hai",
      "1 packet french fries",
      "packet of french fries",
      "french fries ka batao",
      "french fries ka packet",
      "french fries ka kya hisab hai",
      "french fries kitne rupay ka hai",
      "فرینچ فرائز کا ریٹ",
      "فرینچ فرائز کی قیمت",
      "فرینچ فرائز چاہیے"
    ],
    "answer": "• *French Fries* (فرینچ فرائز) 🥟✨\n📦 *Packing:* 450gm\n💰 *Price:* Rs. 250/- per packet\n📝 *Description:* Straight cut crispy potato fries pack 450 grams.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_special-12",
    "patterns": [
      "roll patti kitne ka hai",
      "roll patti ka rate",
      "roll patti price",
      "roll patti ki qeemat",
      "roll patti kitne pcs hote hain",
      "roll patti packet rate",
      "rate of roll patti",
      "price of roll patti",
      "cost of roll patti",
      "roll patti chahiye",
      "roll patti mil jayega",
      "kya roll patti available hai",
      "1 packet roll patti",
      "packet of roll patti",
      "roll patti ka batao",
      "roll patti ka packet",
      "roll patti ka kya hisab hai",
      "roll patti kitne rupay ka hai",
      "رول پٹی کا ریٹ",
      "رول پٹی کی قیمت",
      "رول پٹی چاہیے"
    ],
    "answer": "• *Roll Patti* (رول پٹی) 🥟✨\n📦 *Packing:* 1 kg\n💰 *Price:* Rs. 320/- per packet\n📝 *Description:* Freshly prepared thin spring roll sheets 1 kg pack.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_special-13",
    "patterns": [
      "samosa patti kitne ka hai",
      "samosa patti ka rate",
      "samosa patti price",
      "samosa patti ki qeemat",
      "samosa patti kitne pcs hote hain",
      "samosa patti packet rate",
      "rate of samosa patti",
      "price of samosa patti",
      "cost of samosa patti",
      "samosa patti chahiye",
      "samosa patti mil jayega",
      "kya samosa patti available hai",
      "1 packet samosa patti",
      "packet of samosa patti",
      "samosa patti ka batao",
      "samosa patti ka packet",
      "samosa patti ka kya hisab hai",
      "samosa patti kitne rupay ka hai",
      "سموسہ پٹی کا ریٹ",
      "سموسہ پٹی کی قیمت",
      "سموسہ پٹی چاہیے"
    ],
    "answer": "• *Samosa Patti* (سموسہ پٹی) 🥟✨\n📦 *Packing:* 1 kg\n💰 *Price:* Rs. 320/- per packet\n📝 *Description:* Traditional thin samosa pastry sheets 1 kg pack.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_special-14",
    "patterns": [
      "lachha paratha kitne ka hai",
      "lachha paratha ka rate",
      "lachha paratha price",
      "lachha paratha ki qeemat",
      "lachha paratha kitne pcs hote hain",
      "lachha paratha packet rate",
      "rate of lachha paratha",
      "price of lachha paratha",
      "cost of lachha paratha",
      "lachha paratha chahiye",
      "lachha paratha mil jayega",
      "kya lachha paratha available hai",
      "1 packet lachha paratha",
      "packet of lachha paratha",
      "lachha paratha ka batao",
      "lachha paratha ka packet",
      "lachha paratha ka kya hisab hai",
      "lachha paratha kitne rupay ka hai",
      "لچھا پراٹھا کا ریٹ",
      "لچھا پراٹھا کی قیمت",
      "لچھا پراٹھا چاہیے"
    ],
    "answer": "• *Lachha Paratha* (لچھا پراٹھا) 🥟✨\n📦 *Packing:* 06 pcs\n💰 *Price:* Rs. 220/- per packet\n📝 *Description:* Multi-layered crispy flaky parathas ready on tawa 6 pieces.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "product_special-15",
    "patterns": [
      "plain puri kitne ka hai",
      "plain puri ka rate",
      "plain puri price",
      "plain puri ki qeemat",
      "plain puri kitne pcs hote hain",
      "plain puri packet rate",
      "rate of plain puri",
      "price of plain puri",
      "cost of plain puri",
      "plain puri chahiye",
      "plain puri mil jayega",
      "kya plain puri available hai",
      "1 packet plain puri",
      "packet of plain puri",
      "plain puri ka batao",
      "plain puri ka packet",
      "plain puri ka kya hisab hai",
      "plain puri kitne rupay ka hai",
      "پلین پوری کا ریٹ",
      "پلین پوری کی قیمت",
      "پلین پوری چاہیے"
    ],
    "answer": "• *Plain Puri* (پلین پوری) 🥟✨\n📦 *Packing:* 10 pcs\n💰 *Price:* Rs. 220/- per packet\n📝 *Description:* Soft, puffy, breakfast puris 10 pieces pack.\n✨ *Specialty:* 100% Shariah Halal, ready-to-fry/bake from frozen.\n\nOrder karne ke liye bas packets ki taadad aur apna delivery address bhej dein! (Rs. 5,000 par Free Delivery)"
  },
  {
    "category": "pakora_inquiry",
    "patterns": [
      "pakore hain",
      "pakoray milenge",
      "pakora mix hai",
      "pakora patti",
      "pakora frozen",
      "ramzan items",
      "iftar items",
      "roza kholne ke liye",
      "iftari ke snacks",
      "ramzan package",
      "ramzan deals",
      "pakore ka rate",
      "pakoray ka batao",
      "iftari ke liye kya hai"
    ],
    "answer": "🌙 *Ramzan & Iftari Special Snacks:*\n\nJi haan bhai! Ramzan Mubarak aur chai ke waqt ke liye hamare paas special snacks dastiyab hain:\n• **One-Bite Samosay (Aaloo, Qeema, Chicken, Cheese)** - Iftar dastarkhwan ki ronaq!\n• **Spring Rolls (Mayo Garlic, Malai Boti, Chinese)**\n• **Chicken Vonton & Pizza Samosa**\n• **Samosa Patti & Roll Patti (1 KG Pack Rs. 320/-)** - Ghar par bananay ke liye taza patti!\n• **Hyderi Mix Nimco, Daal Moth & Papdi**\n\nFrozen stock deep freezer me 3 mahine tak fresh rehta hai. Advance Iftar booking ke liye list bhej dein!"
  },
  {
    "category": "nimco_varieties",
    "patterns": [
      "nimco me kya kya hai",
      "nimco ki variety",
      "nimko items",
      "nimco ke rates",
      "taza nimco",
      "daal sev",
      "daal moth",
      "papdi nimco",
      "khatti meethi nimco",
      "chewda",
      "namkeen items",
      "nimco ka dabba",
      "nimco pack",
      "special mix nimco",
      "hyderi mix nimco",
      "nimco delivery",
      "1 kg nimco",
      "adho kilo nimco",
      "nimco kitne ki hai"
    ],
    "answer": "🥜 *New Hyderi Nimco - Famous Authentic Varieties (Since 1970):*\n\n1. **Hyderi Special Mix Nimco:** Humari 50 saala signature recipe, kaju, badam, daal aur crunchy sev ka behtareen mix!\n2. **Daal Moth (Spiced Lentils):** Crispy aur chatpati daal.\n3. **Sev & Papdi:** Chai ke sath khasta crunch.\n4. **Khatti Meethi Nimco:** Mild sweet & tangy balance.\n\n• **Rates:** 250gm, 500gm aur 1 KG packs me rozana taza fry hoti hai.\nAir-tight jar me 2 mahine tak bilkul crispy rehti hai. Kitna pack chahiye aapko?"
  },
  {
    "category": "patti_varieties",
    "patterns": [
      "samosa patti ka rate",
      "roll patti ka rate",
      "patti mil jayegi",
      "manda patti",
      "patti kitne ki hai",
      "1 kg samosa patti",
      "1 kg roll patti",
      "taza patti",
      "patti packet",
      "roll ki patti",
      "samosay ki patti",
      "patti delivery",
      "patti wholesale",
      "patti kitne pcs hoti hai",
      "patti fresh hai"
    ],
    "answer": "🥟 *Fresh Samosa & Roll Patti (100% Fresh Daily Batch):*\n\n• **Samosa Patti (1 KG Pack):** Rs. 320/- (Lagbhag 80–100 thin samosa sheets)\n• **Roll Patti (1 KG Pack):** Rs. 320/- (Lagbhag 40–50 spring roll sheets)\n\n✨ **Quality:** Ultra-thin, non-sticky aur extra crispy. Deep freeze me 2 mahine tak fresh rehti hai.\nKitne KG patti deliver karwani hai aapko?"
  },
  {
    "category": "diet_low_oil",
    "patterns": [
      "diet walon ke liye kya hai",
      "kam tail wala",
      "healthy snacks",
      "oil free",
      "kam calorie",
      "gym walon ke liye",
      "sugar patient ke liye",
      "cholesterol kam",
      "weight loss snacks",
      "steamed items kya hain",
      "bina fry kiye"
    ],
    "answer": "🥗 *Healthy & Low-Oil Options:*\n\n• **Chicken Steamed Momos:** Sirf steam hote hain, zero frying oil!\n• **Chicken Seekh Kabab & Chapli Kabab:** Non-stick pan par sirf 1 chamach oil me grill ho jate hain.\n• **Air Fryer Samosas & Rolls:** Samosa aur Rolls ko 180°C par air fryer me 8-10 minute bake karein (90% oil reduction)!\n• **Chicken Breast Strips:** Pure lean chicken breast protein."
  },
  {
    "category": "school_lunch_special",
    "patterns": [
      "kids tiffin ideas",
      "bachon ke school lunch",
      "tiffin box snack",
      "morning breakfast for kids",
      "nuggets for kids",
      "cheese items for children",
      "lunch box items",
      "bachon ki pasand"
    ],
    "answer": "🎒 *Kids School Tiffin & Lunch Box Specials:*\n\nSubah sirf 5 minute me fry ya air-fry karein:\n• **Chicken Nuggets (Family Pack 24 pcs - Rs. 550/-):** 100% pure chicken breast.\n• **Chicken Popcorn (30 pcs - Rs. 350/-):** Crunchy bite-sized.\n• **Chicken Cheese Balls (12 pcs - Rs. 500/-):** Gooey cheese melt.\n• **Mini Pizza (BBQ & Malai Boti 6 pcs):** Kids absolute favorite.\n• **French Fries (450gm - Rs. 250/-):** Golden crispy fries."
  },
  {
    "category": "area_north_nazimabad",
    "patterns": [
      "north nazimabad me kitni der",
      "hydri market me ho",
      "block e me delivery",
      "sakhi hassan",
      "five star chorangi",
      "kda chaurangi",
      "shadman town",
      "anda mor",
      "buffer zone me delivery"
    ],
    "answer": "🛵 *North Nazimabad & Local Express Delivery:*\n\nJi bhai! Kyunke hamari main branch **Shop # 20-21, Burhani Bagh, Block-E, Hydri** me hi hai, is liye North Nazimabad, Buffer Zone, Sakhi Hassan aur 5-Star par **sirf 30 se 40 minute** me express chilled delivery pohnch jati hai!"
  },
  {
    "category": "area_gulshan_johar",
    "patterns": [
      "gulshan e iqbal delivery",
      "gulistan e johar delivery",
      "jauhar mor",
      "disco bakery",
      "maskan chorangi",
      "nipa chaurangi",
      "millennium mall",
      "kamran chowrangi",
      "safoora",
      "scheme 33"
    ],
    "answer": "🛵 *Gulshan-e-Iqbal & Gulistan-e-Johar Delivery:*\n\nJi haan bhai! Gulshan (Blocks 1–19), Johar (Blocks 1–20), Scheme 33 aur Safoora me same-day temperature-controlled cold box delivery rozana 10 AM se 11 PM tak available hai. Rs. 5,000 par Delivery Free!"
  },
  {
    "category": "area_dha_clifton",
    "patterns": [
      "dha karachi delivery",
      "defence phase 5",
      "phase 6 dha",
      "phase 8",
      "clifton block 2",
      "boat basin",
      "sea view delivery",
      "zamzama",
      "khayaban e shahbaz",
      "badar commercial"
    ],
    "answer": "🛵 *DHA & Clifton Cold-Box Delivery:*\n\nJi haan bilkul! DHA (Phases 1 ta 8) aur Clifton me hamare delivery riders rozana ice-pack cold boxes me frozen items deliver karte hain taake raste me bilkul na pighlein. Cash on Delivery (COD) available hai!"
  },
  {
    "category": "area_malir_cantt",
    "patterns": [
      "malir cantt delivery",
      "cantt karachi",
      "airport ke paas",
      "model colony",
      "gulshan e maymar",
      "bahria town karachi"
    ],
    "answer": "🛵 *Malir Cantt, Model Colony & Outskirts:*\n\nJi haan! Malir Cantt, Model Colony aur Maymar tak chilled delivery rider schedule ke mutabiq same-day deliver karta hai. Rs. 5,000 se baray order par delivery bilkul FREE hai!"
  },
  {
    "category": "tasty_nimco_comparison",
    "patterns": [
      "tasty nimco se behtar hai",
      "tasty nimco jaisa taste",
      "tasty nimco alternative",
      "tasty nimco se kya farq hai",
      "tasty nimco karachi",
      "tasty nimco vs hyderi nimco",
      "hyderi nimco ka taste kaisa hai"
    ],
    "answer": "🏆 *Hyderi Nimco vs Other Brands (Since 1970 Heritage):*\n\nNew Hyderi Nimco 1970 se Burhani Bagh, North Nazimabad me authentic homemade recipes ke sath qaim hai:\n• **Zero Artificial Preservatives:** Rozana fresh batches fry hotay hain.\n• **Light & Crispy Patti:** Commercial brands ki tarah moti patti nahi hoti, ultra-thin patti me pure chicken bharai hoti hai.\n• **Price & Value:** Rs. 350–500 me 24 pieces ka generous pack!\n• **Free Cold Box Delivery:** Rs. 5,000 par poore Karachi me Free Home Delivery."
  },
  {
    "category": "return_complaint_policy",
    "patterns": [
      "agar saman kharab nikla",
      "pighla hua aaya to",
      "taste pasand na aaya to",
      "wapsi hogi",
      "return policy",
      "replace karoge",
      "complaint kahan karein",
      "shikayat hai",
      "rider ne badtameezi ki",
      "packet phata hua tha"
    ],
    "answer": "🛡️ *100% Satisfaction & Replacement Guarantee:*\n\nAapka itmenaan hamari awaleen tarjeeh hai! Agar kisi bhi wajah se:\n1. Parcel raste me pighal gaya ho ya damage hua ho,\n2. Quantity kam ho ya ghalat item aagaya ho,\n\nto foran parcel ki photo WhatsApp helpline **0336-2438422** par share karein. Hum bina kisi jhijhak ke **Free Replacement** bhejenge ya aapki raqam foran refund kar denge!"
  }
];
