import fs from 'fs';
import path from 'path';

const products = [
  // ================= SAMOSA (13 ITEMS) =================
  {
    id: "samosa-1",
    name: "Chicken Vonton",
    nameUrdu: "چکن وانٹون (کرسپی)",
    category: "samosa",
    categoryLabel: "Samosa",
    categoryLabelUrdu: "سموسے",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 240,
    rating: 4.9,
    reviewCount: 94,
    image: "/images/wonton_crispy.jpg",
    badge: "Best Seller",
    badgeUrdu: "سب سے مقبول",
    description: "Crispy golden fried wonton wrappers stuffed with seasoned minced chicken, herbs and signature spices.",
    descriptionUrdu: "کرسپی گولڈن فرائیڈ وانٹون جس میں مصالحہ دار چکن اور روایتی جڑی بوٹیوں کی بھرائی ہے۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "samosa-2",
    name: "Aaloo One Bite Samosa",
    nameUrdu: "آلو ون بائٹ سموسہ",
    category: "samosa",
    categoryLabel: "Samosa",
    categoryLabelUrdu: "سموسے",
    packQuantity: "24 pcs",
    packQuantityUrdu: "۲۴ عدد",
    price: 350,
    rating: 4.8,
    reviewCount: 112,
    image: "/images/samosa_onebite.jpg",
    badge: "Tea Time Fav",
    badgeUrdu: "چائے کا ساتھی",
    description: "Crispy mini bite-sized samosas filled with authentic spiced potato, cumin and coriander blend.",
    descriptionUrdu: "چھوٹے سائز کے کرسپی سموسے، چٹپٹے آلو اور زیرہ دھنیا کے خاص امتزاج کے ساتھ۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "samosa-3",
    name: "Chicken One Bite Samosa",
    nameUrdu: "چکن ون بائٹ سموسہ",
    category: "samosa",
    categoryLabel: "Samosa",
    categoryLabelUrdu: "سموسے",
    packQuantity: "24 pcs",
    packQuantityUrdu: "۲۴ عدد",
    price: 400,
    rating: 4.9,
    reviewCount: 160,
    image: "/images/samosa_onebite.jpg",
    badge: "Top Rated",
    badgeUrdu: "ٹاپ ریٹڈ",
    description: "Delightful bite-sized golden pastry filled with juicy shredded chicken and mild traditional spices.",
    descriptionUrdu: "شاندار چھوٹے چکن سموسے، لذیذ اور رسیلے ریشہ چکن سے بھرپور۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "samosa-4",
    name: "Chicken Cheese Crispy One Bite Samosa",
    nameUrdu: "چکن چیز کرسپی ون بائٹ سموسہ",
    category: "samosa",
    categoryLabel: "Samosa",
    categoryLabelUrdu: "سموسے",
    packQuantity: "24 pcs",
    packQuantityUrdu: "۲۴ عدد",
    price: 500,
    rating: 5.0,
    reviewCount: 210,
    image: "/images/samosa_onebite.jpg",
    badge: "Cheesy Treat",
    badgeUrdu: "چیزی اسپیشل",
    description: "Mouthwatering burst of gooey mozzarella, cheddar and chicken encased in extra crispy mini samosa pastry.",
    descriptionUrdu: "پگھلتی ہوئی موزریلا اور چیڈر پنیر اور چکن سے بھرپور کرسپی سموسہ۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "samosa-5",
    name: "Chicken Cone Samosa",
    nameUrdu: "چکن کون سموسہ",
    category: "samosa",
    categoryLabel: "Samosa",
    categoryLabelUrdu: "سموسے",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 350,
    rating: 4.7,
    reviewCount: 65,
    image: "/images/samosa_classic.jpg",
    badge: "Special Cone",
    badgeUrdu: "کون شیپ",
    description: "Unique handcrafted crunchy cone-shaped pastry loaded with rich spicy chicken filling.",
    descriptionUrdu: "منفرد کون کی شکل میں بنا کرسپی سموسہ جس میں لذیذ چکن بھرا گیا ہے۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "samosa-6",
    name: "Chicken Malai Boti Samosa",
    nameUrdu: "چکن ملائی بوٹی سموسہ",
    category: "samosa",
    categoryLabel: "Samosa",
    categoryLabelUrdu: "سموسے",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 500,
    rating: 4.9,
    reviewCount: 140,
    image: "/images/samosa_classic.jpg",
    badge: "Creamy Melt",
    badgeUrdu: "ملائی بوٹی",
    description: "Tender chicken cooked in rich cream, green chilies, yogurt and mild spices packed in crispy pastry.",
    descriptionUrdu: "کریمی ملائی اور ہلکے مسالوں میں پکا چکن، کرسپی پٹی میں بند۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "samosa-7",
    name: "Chicken Bar B Q Samosa",
    nameUrdu: "چکن بار بی کیو سموسہ",
    category: "samosa",
    categoryLabel: "Samosa",
    categoryLabelUrdu: "سموسے",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 500,
    rating: 4.8,
    reviewCount: 125,
    image: "/images/samosa_classic.jpg",
    badge: "Smoky BBQ",
    badgeUrdu: "بار بی کیو",
    description: "Authentic charcoal-smoked BBQ spiced chicken chunks stuffed in traditional samosa wrapper.",
    descriptionUrdu: "کوئلے کے دھوئیں کا اصلی اسموکی ذائقہ اور مصالحہ دار چکن سموسہ۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "samosa-8",
    name: "Chicken Pizza Samosa",
    nameUrdu: "چکن پیزا سموسہ",
    category: "samosa",
    categoryLabel: "Samosa",
    categoryLabelUrdu: "سموسے",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 550,
    rating: 4.9,
    reviewCount: 175,
    image: "/images/samosa_classic.jpg",
    badge: "Italian Fusion",
    badgeUrdu: "پیزا فلیور",
    description: "Fusion samosa with Italian herbs, pizza sauce, mozzarella cheese, capsicum, olives and chicken.",
    descriptionUrdu: "پیزا ساس، شملہ مرچ، زیتون، چیز اور چکن سے تیار کردہ جدید سموسہ۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "samosa-9",
    name: "Chicken Cheese Crispy Samosa",
    nameUrdu: "چکن چیز کرسپی سموسہ",
    category: "samosa",
    categoryLabel: "Samosa",
    categoryLabelUrdu: "سموسے",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 400,
    rating: 4.8,
    reviewCount: 130,
    image: "/images/samosa_classic.jpg",
    badge: "Extra Cheesy",
    badgeUrdu: "چیزی کرسپی",
    description: "Premium cheese blend with shredded chicken in an ultra-crunchy triangular crust.",
    descriptionUrdu: "خالص پنیر اور چکن کی لذیذ بھروائی کے ساتھ خستہ سموسہ۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "samosa-10",
    name: "Chicken Chinese Samosa",
    nameUrdu: "چکن چائنیز سموسہ",
    category: "samosa",
    categoryLabel: "Samosa",
    categoryLabelUrdu: "سموسے",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 350,
    rating: 4.7,
    reviewCount: 92,
    image: "/images/samosa_classic.jpg",
    badge: "Chowmein Style",
    badgeUrdu: "چائنیز",
    description: "Stir-fried shredded vegetables, soy sauce, black pepper and chicken stuffed samosa.",
    descriptionUrdu: "چائنیز سبزیاں، چکن اور کالی مرچ و سویا ساس کے ساتھ تیار کردہ۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "samosa-11",
    name: "Qeema Samosa",
    nameUrdu: "قیمہ سموسہ (بیف / مٹن)",
    category: "samosa",
    categoryLabel: "Samosa",
    categoryLabelUrdu: "سموسے",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 350,
    rating: 4.9,
    reviewCount: 180,
    image: "/images/samosa_classic.jpg",
    badge: "Traditional",
    badgeUrdu: "روایتی قیمہ",
    description: "Traditional Karachi-style finely minced beef seasoned with onion, mint, green chilies and garam masala.",
    descriptionUrdu: "خالص قیمہ، پودینہ اور ہری مرچوں سے سجا روایتی کراچی سموسہ۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "samosa-12",
    name: "Aaloo Samosa",
    nameUrdu: "آلو سموسہ (ریگولر)",
    category: "samosa",
    categoryLabel: "Samosa",
    categoryLabelUrdu: "سموسے",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 300,
    rating: 4.7,
    reviewCount: 88,
    image: "/images/samosa_classic.jpg",
    badge: "Classic",
    badgeUrdu: "کلاسک آلو",
    description: "Classic golden potato samosa with whole coriander, cumin, crushed red pepper and fresh mint.",
    descriptionUrdu: "ثابت دھنیا اور زیرہ کے مصالحے دار آلو والا کلاسک سموسہ۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "samosa-13",
    name: "Daal Samosa",
    nameUrdu: "دال سموسہ (کرسپی)",
    category: "samosa",
    categoryLabel: "Samosa",
    categoryLabelUrdu: "سموسے",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 300,
    rating: 4.6,
    reviewCount: 74,
    image: "/images/samosa_classic.jpg",
    badge: "Crunchy Daal",
    badgeUrdu: "دال سموسہ",
    description: "Spiced split yellow lentil filling packed in paper-thin crunchy triangular wrapper.",
    descriptionUrdu: "چٹپٹی دال کی بھروائی کے ساتھ نہایت خستہ اور لذیذ سموسہ۔",
    isAvailable: true,
    featured: false
  },

  // ================= ROLL (13 ITEMS) =================
  {
    id: "roll-1",
    name: "Chicken One Bite Roll",
    nameUrdu: "چکن ون بائٹ رول",
    category: "roll",
    categoryLabel: "Roll",
    categoryLabelUrdu: "اسپرنگ رولز",
    packQuantity: "24 pcs",
    packQuantityUrdu: "۲۴ عدد",
    price: 500,
    rating: 4.9,
    reviewCount: 155,
    image: "/images/spring_roll_crispy.jpg",
    badge: "Party Hit",
    badgeUrdu: "پارٹی ہٹ",
    description: "Crispy miniature spring rolls packed with seasoned chicken and crunchy vegetables.",
    descriptionUrdu: "چھوٹے سائز کے کرسپی اسپرنگ رولز، چکن اور سبزیوں سے بھرپور۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "roll-2",
    name: "Chicken Cheese Crispy One Bite Roll",
    nameUrdu: "چکن چیز کرسپی ون بائٹ رول",
    category: "roll",
    categoryLabel: "Roll",
    categoryLabelUrdu: "اسپرنگ رولز",
    packQuantity: "24 pcs",
    packQuantityUrdu: "۲۴ عدد",
    price: 550,
    rating: 5.0,
    reviewCount: 190,
    image: "/images/spring_roll_crispy.jpg",
    badge: "Cheesy Bite",
    badgeUrdu: "چیزی ون بائٹ",
    description: "Extra crunchy mini rolls oozing with premium cheese and succulent chicken.",
    descriptionUrdu: "چیڈر اور موزریلا چیز کے ساتھ کرسپی ون بائٹ چکن رولز۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "roll-3",
    name: "Chicken Bar B Q Roll",
    nameUrdu: "چکن بار بی کیو رول",
    category: "roll",
    categoryLabel: "Roll",
    categoryLabelUrdu: "اسپرنگ رولز",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 500,
    rating: 4.8,
    reviewCount: 110,
    image: "/images/spring_roll_golden.jpg",
    badge: "Smoky Taste",
    badgeUrdu: "بار بی کیو",
    description: "Smoky charcoal BBQ chicken wrapped in crisp handmade pastry rolls.",
    descriptionUrdu: "بار بی کیو کے اسموکی ذائقے دار چکن سے بھرے اسپرنگ رولز۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "roll-4",
    name: "Chicken Malai Boti Roll",
    nameUrdu: "چکن ملائی بوٹی رول",
    category: "roll",
    categoryLabel: "Roll",
    categoryLabelUrdu: "اسپرنگ رولز",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 500,
    rating: 4.9,
    reviewCount: 165,
    image: "/images/spring_roll_golden.jpg",
    badge: "Creamy Malai",
    badgeUrdu: "ملائی بوٹی",
    description: "Rich creamy marinated chicken filling wrapped in a golden crispy roll.",
    descriptionUrdu: "ملائی بوٹی کے رسیلے چکن سے سجے خاص رولز۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "roll-5",
    name: "Chicken Malai Boti One Bite Roll",
    nameUrdu: "چکن ملائی بوٹی ون بائٹ رول",
    category: "roll",
    categoryLabel: "Roll",
    categoryLabelUrdu: "اسپرنگ رولز",
    packQuantity: "24 pcs",
    packQuantityUrdu: "۲۴ عدد",
    price: 500,
    rating: 4.9,
    reviewCount: 135,
    image: "/images/spring_roll_crispy.jpg",
    badge: "Mini Malai",
    badgeUrdu: "ون بائٹ ملائی",
    description: "Bite-sized creamy chicken malai boti rolls, ideal for high tea and events.",
    descriptionUrdu: "چھوٹے ون بائٹ رولز، ملائی بوٹی کے نرم ذائقے کے ساتھ۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "roll-6",
    name: "Chicken Pizza Roll",
    nameUrdu: "چکن پیزا رول",
    category: "roll",
    categoryLabel: "Roll",
    categoryLabelUrdu: "اسپرنگ رولز",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 550,
    rating: 4.9,
    reviewCount: 145,
    image: "/images/spring_roll_golden.jpg",
    badge: "Pizza Flavor",
    badgeUrdu: "پیزا فلیور",
    description: "Pizza-sauce infused chicken, oregano, melted cheese, and capsicum in a crispy roll.",
    descriptionUrdu: "پیزا ساس، شملہ مرچ، زیتون اور چیز کا لذیذ چکن رول۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "roll-7",
    name: "Chicken Mayo Garlic Roll",
    nameUrdu: "چکن مایو گارلک رول",
    category: "roll",
    categoryLabel: "Roll",
    categoryLabelUrdu: "اسپرنگ رولز",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 500,
    rating: 4.8,
    reviewCount: 120,
    image: "/images/spring_roll_golden.jpg",
    badge: "Garlic Mayo",
    badgeUrdu: "مایو گارلک",
    description: "Creamy garlic mayonnaise tossed with tender chicken chunks in a crispy shell.",
    descriptionUrdu: "مایو گارلک ساس اور ریشہ چکن سے بھرا کرسپی رول۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "roll-8",
    name: "Chicken Cheese Crispy Roll",
    nameUrdu: "چکن چیز کرسپی رول",
    category: "roll",
    categoryLabel: "Roll",
    categoryLabelUrdu: "اسپرنگ رولز",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 400,
    rating: 4.8,
    reviewCount: 105,
    image: "/images/spring_roll_golden.jpg",
    badge: "Cheesy",
    badgeUrdu: "چیز کرسپی",
    description: "Golden crispy roll with melting mozzarella and seasoned chicken.",
    descriptionUrdu: "موزریلا پنیر اور چکن کی خستہ اور لذیذ جوڑی۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "roll-9",
    name: "Chicken Shahi Roll",
    nameUrdu: "چکن شاہی رول",
    category: "roll",
    categoryLabel: "Roll",
    categoryLabelUrdu: "اسپرنگ رولز",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 350,
    rating: 4.7,
    reviewCount: 95,
    image: "/images/spring_roll_golden.jpg",
    badge: "Royal Taste",
    badgeUrdu: "شاہی ذائقہ",
    description: "Rich royal recipe with delicately spiced chicken and dry nuts aroma.",
    descriptionUrdu: "خاص شاہی مصالحوں اور چکن سے تیار کردہ روایتی رول۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "roll-10",
    name: "Chicken Mint Roll",
    nameUrdu: "چکن منٹ رول (پودینہ)",
    category: "roll",
    categoryLabel: "Roll",
    categoryLabelUrdu: "اسپرنگ رولز",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 350,
    rating: 4.7,
    reviewCount: 88,
    image: "/images/spring_roll_golden.jpg",
    badge: "Fresh Mint",
    badgeUrdu: "پودینہ فلیور",
    description: "Fresh garden mint and green herb chicken filling inside crispy pastry.",
    descriptionUrdu: "تازہ پودینے اور ہری چٹنی کے امتزاج سے تیار چکن رول۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "roll-11",
    name: "Chicken Chinese Roll",
    nameUrdu: "چکن چائنیز رول",
    category: "roll",
    categoryLabel: "Roll",
    categoryLabelUrdu: "اسپرنگ رولز",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 350,
    rating: 4.7,
    reviewCount: 82,
    image: "/images/spring_roll_golden.jpg",
    badge: "Chinese Style",
    badgeUrdu: "چائنیز",
    description: "Shredded chicken and julienne vegetables seasoned with soy sauce and black pepper.",
    descriptionUrdu: "چکن اور بند گوبھی، گاجر اور سویا ساس کے ساتھ کلاسک چائنیز رول۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "roll-12",
    name: "Chicken Bread Roll",
    nameUrdu: "چکن بریڈ رول",
    category: "roll",
    categoryLabel: "Roll",
    categoryLabelUrdu: "اسپرنگ رولز",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 300,
    rating: 4.8,
    reviewCount: 78,
    image: "/images/spring_roll_golden.jpg",
    badge: "Bread Coated",
    badgeUrdu: "بریڈ رول",
    description: "Soft bread rolled around savory chicken, coated in crispy breadcrumbs.",
    descriptionUrdu: "بریڈ کرمبز کی کوٹنگ میں خستہ چکن بریڈ رول۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "roll-13",
    name: "Chicken Chimmy Changa",
    nameUrdu: "چکن چمی چانگا (میکسیکن)",
    category: "roll",
    categoryLabel: "Roll",
    categoryLabelUrdu: "اسپرنگ رولز",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 350,
    rating: 4.8,
    reviewCount: 90,
    image: "/images/spring_roll_golden.jpg",
    badge: "Mexican Style",
    badgeUrdu: "چمی چانگا",
    description: "Mexican style deep-fried stuffed pocket loaded with spicy chicken, peppers and salsa seasoning.",
    descriptionUrdu: "میکسیکن ذائقے کی چکن پاکٹ، تلی ہوئی اور مسالے دار۔",
    isAvailable: true,
    featured: false
  },

  // ================= KABAB & MOMOS (11 ITEMS) =================
  {
    id: "kabab-1",
    name: "Chicken Shami Kabab",
    nameUrdu: "چکن شامی کباب",
    category: "kabab",
    categoryLabel: "Kabab",
    categoryLabelUrdu: "کباب اور موموز",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 600,
    rating: 4.9,
    reviewCount: 220,
    image: "/images/shami_kabab_real.jpg",
    badge: "Best Seller",
    badgeUrdu: "سب سے مقبول",
    description: "Melt-in-mouth chicken shami patties made with split yellow gram and fragrant whole spices.",
    descriptionUrdu: "چکن اور چنے کی دال کے اصلی ریشے دار شامی کباب۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "kabab-2",
    name: "Beef Shami Kabab",
    nameUrdu: "بیف شامی کباب (روایتی)",
    category: "kabab",
    categoryLabel: "Kabab",
    categoryLabelUrdu: "کباب اور موموز",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 600,
    rating: 5.0,
    reviewCount: 245,
    image: "/images/shami_kabab_real.jpg",
    badge: "Authentic Beef",
    badgeUrdu: "خالص بیف",
    description: "Authentic Karachi beef shami kababs with tender shredded beef texture and traditional aromatics.",
    descriptionUrdu: "خالص بچھیا کے گوشت سے بنے ہوئے لذیذ اور ریشمی شامی کباب۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "kabab-3",
    name: "Chicken Seekh Kabab",
    nameUrdu: "چکن سیخ کباب (بار بی کیو)",
    category: "kabab",
    categoryLabel: "Kabab",
    categoryLabelUrdu: "کباب اور موموز",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 650,
    rating: 4.9,
    reviewCount: 185,
    image: "/images/seekh_kabab_real.jpg",
    badge: "Charcoal BBQ",
    badgeUrdu: "سیخ کباب",
    description: "Finely minced chicken flavored with ginger, garlic, coriander, roasted cumin and BBQ smoke.",
    descriptionUrdu: "خوشبودار مصالحوں اور کوئلے کی خوشبو سے سجے چکن سیخ کباب۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "kabab-4",
    name: "Chicken Chapli Kabab",
    nameUrdu: "چکن چپلی کباب",
    category: "kabab",
    categoryLabel: "Kabab",
    categoryLabelUrdu: "کباب اور موموز",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 500,
    rating: 4.8,
    reviewCount: 140,
    image: "/images/chapli_kabab_real.jpg",
    badge: "Peshawari",
    badgeUrdu: "چپلی کباب",
    description: "Peshawari style pan-fried chicken patty with crushed pomegranate seeds, tomato and coriander.",
    descriptionUrdu: "اناردانہ اور ٹماٹر کے چٹپٹے مسالوں سے مزین چکن چپلی کباب۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "kabab-5",
    name: "Beef Chapli Kabab",
    nameUrdu: "بیف چپلی کباب (پشاوری)",
    category: "kabab",
    categoryLabel: "Kabab",
    categoryLabelUrdu: "کباب اور موموز",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 500,
    rating: 4.9,
    reviewCount: 160,
    image: "/images/chapli_kabab_real.jpg",
    badge: "Special Beef",
    badgeUrdu: "بیف چپلی",
    description: "Traditional spiced beef patty infused with coriander seeds, chili flakes, mint and butter.",
    descriptionUrdu: "اصلی پشاوری بیف چپلی کباب، چٹپٹا اور رسیلا۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "kabab-6",
    name: "Chicken Burger Patty",
    nameUrdu: "چکن برگر پیٹی",
    category: "kabab",
    categoryLabel: "Kabab",
    categoryLabelUrdu: "کباب اور موموز",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 400,
    rating: 4.7,
    reviewCount: 98,
    image: "/images/shami_kabab_real.jpg",
    badge: "Burger Ready",
    badgeUrdu: "برگر پیٹی",
    description: "Juicy chicken burger patties prepared with mild spices, perfect for homemade burgers.",
    descriptionUrdu: "گھر کے مزیدار برگرز کے لیے تیار رسیلی چکن پیٹی۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "kabab-7",
    name: "Chicken Cutless",
    nameUrdu: "چکن کٹلس (کرسپی)",
    category: "kabab",
    categoryLabel: "Kabab",
    categoryLabelUrdu: "کباب اور موموز",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 500,
    rating: 4.8,
    reviewCount: 115,
    image: "/images/shami_kabab_real.jpg",
    badge: "Potato & Chicken",
    badgeUrdu: "کٹلس",
    description: "Crispy breadcrumb coated mashed potato and chicken patties seasoned with green chilies and herbs.",
    descriptionUrdu: "آلو اور چکن کے مصالحہ دار مکسچر سے بنے کرسپی کٹلس۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "kabab-8",
    name: "Chicken Stick",
    nameUrdu: "چکن اسٹک",
    category: "kabab",
    categoryLabel: "Kabab",
    categoryLabelUrdu: "کباب اور موموز",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 550,
    rating: 4.8,
    reviewCount: 102,
    image: "/images/seekh_kabab_real.jpg",
    badge: "Skewers",
    badgeUrdu: "اسٹک",
    description: "Marinated juicy chicken chunks on skewers coated in seasoned batter ready to fry.",
    descriptionUrdu: "سیخ پر لگے مسالے دار چکن باؤلز، فرائی کے لیے تیار۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "kabab-9",
    name: "Chicken Kofta",
    nameUrdu: "چکن کوفتہ (گریوی ریڈی)",
    category: "kabab",
    categoryLabel: "Kabab",
    categoryLabelUrdu: "کباب اور موموز",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 500,
    rating: 4.7,
    reviewCount: 88,
    image: "/images/shami_kabab_real.jpg",
    badge: "Meatballs",
    badgeUrdu: "کوفتے",
    description: "Succulent chicken meatballs blended with aromatic herbs, ready for curries or frying.",
    descriptionUrdu: "سالن یا فرائی کے لیے تیار نرم اور رسیلے چکن کوفتے۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "kabab-10",
    name: "Chicken Momos (Steamed)",
    nameUrdu: "چکن موموز (اسٹیمڈ)",
    category: "kabab",
    categoryLabel: "Kabab",
    categoryLabelUrdu: "کباب اور موموز",
    packQuantity: "10 pcs",
    packQuantityUrdu: "۱۰ عدد",
    price: 400,
    rating: 4.9,
    reviewCount: 195,
    image: "/images/momos_steamed_real.jpg",
    badge: "Dumplings",
    badgeUrdu: "اسٹیمڈ موموز",
    description: "Delicate steamed dumplings bursting with seasoned minced chicken, ginger and spring onions.",
    descriptionUrdu: "بہت نرم اور رسیلے چکن دم پخت موموز (اسٹیمڈ ڈمپلنگز)۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "kabab-11",
    name: "Chicken Momos (Fried)",
    nameUrdu: "چکن موموز (فرائیڈ)",
    category: "kabab",
    categoryLabel: "Kabab",
    categoryLabelUrdu: "کباب اور موموز",
    packQuantity: "08 pcs",
    packQuantityUrdu: "۰۸ عدد",
    price: 400,
    rating: 4.9,
    reviewCount: 170,
    image: "/images/momos_fried_real.jpg",
    badge: "Crispy Momos",
    badgeUrdu: "فرائیڈ موموز",
    description: "Golden pan-fried crunchy momos stuffed with juicy minced chicken and spices.",
    descriptionUrdu: "کرسپی اور چٹپٹے تلے ہوئے چکن موموز۔",
    isAvailable: true,
    featured: true
  },

  // ================= PIZZA (2 ITEMS) =================
  {
    id: "pizza-1",
    name: "B.B.Q Mini Pizza",
    nameUrdu: "بی بی کیو منی پیزا",
    category: "pizza",
    categoryLabel: "Pizza",
    categoryLabelUrdu: "منی پیزا",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 450,
    rating: 4.9,
    reviewCount: 160,
    image: "/images/mini_pizza_real.jpg",
    badge: "BBQ Pizza",
    badgeUrdu: "بار بی کیو پیزا",
    description: "Fluffy pizza dough topped with smoky BBQ chicken, marinara sauce, herbs, and mozzarella cheese.",
    descriptionUrdu: "بار بی کیو چکن، پیزا ساس اور وافر موزریلا پنیر سے سجا منی پیزا (۶ عدد)۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "pizza-2",
    name: "Malai Boti Mini Pizza",
    nameUrdu: "ملائی بوٹی منی پیزا",
    category: "pizza",
    categoryLabel: "Pizza",
    categoryLabelUrdu: "منی پیزا",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 500,
    rating: 5.0,
    reviewCount: 185,
    image: "/images/mini_pizza_real.jpg",
    badge: "Creamy Pizza",
    badgeUrdu: "ملائی بوٹی پیزا",
    description: "Rich creamy malai chicken boti topping with white garlic sauce and premium melted cheese.",
    descriptionUrdu: "ملائی بوٹی چکن اور کریمی چیڈر و موزریلا چیز کے ساتھ اسپیشل منی پیزا (۶ عدد)۔",
    isAvailable: true,
    featured: true
  },

  // ================= OTHER SPECIAL (15 ITEMS) =================
  {
    id: "special-1",
    name: "Hot Shot",
    nameUrdu: "ہاٹ شاٹس (کرسپی چکن)",
    category: "special",
    categoryLabel: "Other Special",
    categoryLabelUrdu: "اسپیشل آئٹمز",
    packQuantity: "250gm - 06 pcs",
    packQuantityUrdu: "۲۵۰ گرام (۰۶ عدد)",
    price: 450,
    rating: 4.8,
    reviewCount: 130,
    image: "/images/nuggets_real.jpg",
    badge: "Spicy Crunch",
    badgeUrdu: "ہاٹ شاٹس",
    description: "Spicy battered bite-sized whole chicken breast chunks, fried to crispy perfection.",
    descriptionUrdu: "اسپائسی کرسپی چکن بائٹس، بچوں اور نوجوانوں کی پسندیدہ۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "special-2",
    name: "Chicken Nuggets Big",
    nameUrdu: "چکن نگٹس (بڑا پیک)",
    category: "special",
    categoryLabel: "Other Special",
    categoryLabelUrdu: "اسپیشل آئٹمز",
    packQuantity: "24 pcs",
    packQuantityUrdu: "۲۴ عدد",
    price: 550,
    rating: 4.9,
    reviewCount: 215,
    image: "/images/nuggets_real.jpg",
    badge: "Family Pack",
    badgeUrdu: "فیملی پیک",
    description: "Golden crumbed pure chicken breast nuggets, tender inside and ultra-crunchy outside.",
    descriptionUrdu: "خالص چکن بریسٹ سے تیار کردہ گولڈن نگٹس فیملی پیک (۲۴ عدد)۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "special-3",
    name: "Chicken Nuggets Small",
    nameUrdu: "چکن نگٹس (چھوٹا پیک)",
    category: "special",
    categoryLabel: "Other Special",
    categoryLabelUrdu: "اسپیشل آئٹمز",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 300,
    rating: 4.8,
    reviewCount: 140,
    image: "/images/nuggets_real.jpg",
    badge: "Kids Favorite",
    badgeUrdu: "نگٹس",
    description: "Crispy chicken nuggets made with 100% halal chicken and seasoned breading.",
    descriptionUrdu: "خالص چکن کے ۱۲ عدد کرسپی نگٹس کا پیک۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "special-4",
    name: "Chicken Cheese Ball",
    nameUrdu: "چکن چیز بولز",
    category: "special",
    categoryLabel: "Other Special",
    categoryLabelUrdu: "اسپیشل آئٹمز",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 500,
    rating: 4.9,
    reviewCount: 175,
    image: "/images/nuggets_real.jpg",
    badge: "Cheese Burst",
    badgeUrdu: "چیز بولز",
    description: "Crispy spheres packed with gooey cheese and minced chicken that bursts in your mouth.",
    descriptionUrdu: "پگھلتی چیز اور مصالحہ دار چکن کے گولڈن فرائیڈ بولز۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "special-5",
    name: "Chicken Cheese Lolypop",
    nameUrdu: "چکن چیز لولی پاپ",
    category: "special",
    categoryLabel: "Other Special",
    categoryLabelUrdu: "اسپیشل آئٹمز",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 350,
    rating: 4.8,
    reviewCount: 110,
    image: "/images/nuggets_real.jpg",
    badge: "Fun Treat",
    badgeUrdu: "لولی پاپ",
    description: "Chicken lollipop drumsticks stuffed with mozzarella cheese, crumbed and ready to fry.",
    descriptionUrdu: "چیز سے بھرے خستہ چکن لولی پاپس۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "special-6",
    name: "Chicken Donuts",
    nameUrdu: "چکن ڈونٹس (چیزی)",
    category: "special",
    categoryLabel: "Other Special",
    categoryLabelUrdu: "اسپیشل آئٹمز",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 500,
    rating: 4.8,
    reviewCount: 155,
    image: "/images/nuggets_real.jpg",
    badge: "Unique",
    badgeUrdu: "چکن ڈونٹس",
    description: "Savory ring-shaped chicken patties coated in breadcrumbs, perfect for tea time.",
    descriptionUrdu: "منفرد ڈونٹ شیپ میں بنے ہوئے کرسپی چکن پیٹیز۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "special-7",
    name: "Chicken Finger",
    nameUrdu: "چکن فنگرز",
    category: "special",
    categoryLabel: "Other Special",
    categoryLabelUrdu: "اسپیشل آئٹمز",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 400,
    rating: 4.7,
    reviewCount: 95,
    image: "/images/nuggets_real.jpg",
    badge: "Crispy Strips",
    badgeUrdu: "فنگرز",
    description: "Tender seasoned chicken strips encased in a crunchy golden breading.",
    descriptionUrdu: "رسیلے چکن اسٹرپس کرسپی کوٹنگ کے ساتھ۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "special-8",
    name: "Chicken Popcorn",
    nameUrdu: "چکن پاپ کارن (بائٹس)",
    category: "special",
    categoryLabel: "Other Special",
    categoryLabelUrdu: "اسپیشل آئٹمز",
    packQuantity: "30 pcs",
    packQuantityUrdu: "۳۰ عدد",
    price: 350,
    rating: 4.8,
    reviewCount: 135,
    image: "/images/nuggets_real.jpg",
    badge: "Movie Snack",
    badgeUrdu: "پاپ کارن",
    description: "Bite-sized crunchy spiced popcorn chicken pieces, 30 pieces pack.",
    descriptionUrdu: "چھوٹے سائز کے کرسپی چکن پاپ کارن بائٹس (۳۰ عدد)۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "special-9",
    name: "Chicken Chillos",
    nameUrdu: "چکن چیلووز",
    category: "special",
    categoryLabel: "Other Special",
    categoryLabelUrdu: "اسپیشل آئٹمز",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 350,
    rating: 4.7,
    reviewCount: 80,
    image: "/images/nuggets_real.jpg",
    badge: "Spicy Bites",
    badgeUrdu: "چیلووز",
    description: "Green chili and chicken stuffed crispy patties with a zesty kick.",
    descriptionUrdu: "ہری مرچ اور مصالحہ دار چکن سے بنے اسپیشل چیلووز۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "special-10",
    name: "Chicken Pizza Puff",
    nameUrdu: "چکن پیزا پف",
    category: "special",
    categoryLabel: "Other Special",
    categoryLabelUrdu: "اسپیشل آئٹمز",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 450,
    rating: 4.8,
    reviewCount: 120,
    image: "/images/mini_pizza_real.jpg",
    badge: "Flaky Puff",
    badgeUrdu: "پیزا پف",
    description: "Flaky layered puff pastry stuffed with pizza sauce, cheese and diced chicken.",
    descriptionUrdu: "پف پیسٹری میں بند پیزا ساس اور چکن چیز کی بھرائی۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "special-11",
    name: "French Fries",
    nameUrdu: "فرینچ فرائز (کرسپی آلو)",
    category: "special",
    categoryLabel: "Other Special",
    categoryLabelUrdu: "اسپیشل آئٹمز",
    packQuantity: "450gm",
    packQuantityUrdu: "۴۵۰ گرام",
    price: 250,
    rating: 4.7,
    reviewCount: 110,
    image: "/images/french_fries_real.jpg",
    badge: "Crispy Potato",
    badgeUrdu: "فرائز",
    description: "Straight cut potato fries, flash-frozen to retain maximum crispiness upon frying.",
    descriptionUrdu: "تازہ اور خستہ کٹ پوٹیٹو فرائز (۴۵۰ گرام)۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "special-12",
    name: "Roll Patti",
    nameUrdu: "رول پٹی (تازہ کلو پیک)",
    category: "special",
    categoryLabel: "Other Special",
    categoryLabelUrdu: "اسپیشل آئٹمز",
    packQuantity: "1 kg",
    packQuantityUrdu: "۱ کلو",
    price: 320,
    rating: 4.9,
    reviewCount: 190,
    image: "/images/paratha_real.jpg",
    badge: "100% Fresh",
    badgeUrdu: "تازہ پٹی",
    description: "Freshly prepared thin and pliable spring roll sheets, non-stick and easy to roll.",
    descriptionUrdu: "گھر پر رول بنانے کے لیے بہترین اور باریک رول پٹی (۱ کلو پیک)۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "special-13",
    name: "Samosa Patti",
    nameUrdu: "سموسہ پٹی (تازہ کلو پیک)",
    category: "special",
    categoryLabel: "Other Special",
    categoryLabelUrdu: "اسپیشل آئٹمز",
    packQuantity: "1 kg",
    packQuantityUrdu: "۱ کلو",
    price: 320,
    rating: 4.9,
    reviewCount: 205,
    image: "/images/paratha_real.jpg",
    badge: "100% Fresh",
    badgeUrdu: "سموسہ پٹی",
    description: "Traditional paper-thin samosa pastry sheets, yields extra crisp and dry samosas.",
    descriptionUrdu: "خستہ اور لذیذ سموسوں کے لیے مشہور حیدری سموسہ پٹی (۱ کلو پیک)۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "special-14",
    name: "Lachha Paratha",
    nameUrdu: "لچھا پراٹھا (فروزن)",
    category: "special",
    categoryLabel: "Other Special",
    categoryLabelUrdu: "اسپیشل آئٹمز",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 220,
    rating: 4.9,
    reviewCount: 180,
    image: "/images/paratha_real.jpg",
    badge: "Multi-Layered",
    badgeUrdu: "لچھا پراٹھا",
    description: "Authentic multi-layered crispy flaky parathas, ready on tawa in 2 minutes.",
    descriptionUrdu: "پرت دار خستہ لچھا پراٹھا، توے پر صرف ۲ منٹ میں تیار (۶ عدد)۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "special-15",
    name: "Plain Puri",
    nameUrdu: "پلین پوری (حلوہ پوری اسپیشل)",
    category: "special",
    categoryLabel: "Other Special",
    categoryLabelUrdu: "اسپیشل آئٹمز",
    packQuantity: "10 pcs",
    packQuantityUrdu: "۱۰ عدد",
    price: 220,
    rating: 4.8,
    reviewCount: 130,
    image: "/images/paratha_real.jpg",
    badge: "Soft & Fluffy",
    badgeUrdu: "پوری",
    description: "Soft, puffy, traditional breakfast puris, fries in 30 seconds to golden fluffiness.",
    descriptionUrdu: "ناشتے کے لیے نرم اور پھولی ہوئی روایتی پوریاں (۱۰ عدد)۔",
    isAvailable: true,
    featured: false
  },

  // ================= HYDERI NIMCO (4 ITEMS) =================
  {
    id: "nimco-1",
    name: "Special Hyderi Mix Nimco (500g)",
    nameUrdu: "اسپیشل حیدری مکس نمکو (۵۰۰ گرام)",
    category: "nimco",
    categoryLabel: "Hyderi Nimco",
    categoryLabelUrdu: "حیدری نمکو",
    packQuantity: "500g",
    packQuantityUrdu: "۵۰۰ گرام",
    price: 400,
    rating: 5.0,
    reviewCount: 310,
    image: "/images/nimco_real.jpg",
    badge: "Since 1970",
    badgeUrdu: "۱۹۷۰ سے مشہور",
    description: "Our iconic Karachi-famous blend of spicy sev, roasted peanuts, fried lentils and secret spices.",
    descriptionUrdu: "۱۹۷۰ سے کراچی کا سب سے مشہور چٹپٹا مکس نمکو، مونگ پھلی اور کرنچی سیو کے ساتھ۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "nimco-2",
    name: "Special Hyderi Mix Nimco (1 kg)",
    nameUrdu: "اسپیشل حیدری مکس نمکو (۱ کلو فیملی جار)",
    category: "nimco",
    categoryLabel: "Hyderi Nimco",
    categoryLabelUrdu: "حیدری نمکو",
    packQuantity: "1 kg",
    packQuantityUrdu: "۱ کلو",
    price: 750,
    rating: 5.0,
    reviewCount: 420,
    image: "/images/nimco_real.jpg",
    badge: "Best Value Jar",
    badgeUrdu: "فیملی جار",
    description: "1 Kg jumbo sealed family pack of Karachi's authentic Hyderi Nimco.",
    descriptionUrdu: "پورے خاندان کے لیے ۱ کلو کا بڑا پیک، ہمیشہ تازہ اور خستہ۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "nimco-3",
    name: "Daal Moth Nimco",
    nameUrdu: "دال موٹھ نمکو (۵۰۰ گرام)",
    category: "nimco",
    categoryLabel: "Hyderi Nimco",
    categoryLabelUrdu: "حیدری نمکو",
    packQuantity: "500g",
    packQuantityUrdu: "۵۰۰ گرام",
    price: 400,
    rating: 4.9,
    reviewCount: 165,
    image: "/images/nimco_real.jpg",
    badge: "Crunchy Daal",
    badgeUrdu: "دال موٹھ",
    description: "Fried spiced lentils and crunchy sev seasoned with Himalayan black salt.",
    descriptionUrdu: "کالے نمک اور خاص مصالحوں سے تیار کردہ خستہ دال موٹھ۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "nimco-4",
    name: "Spicy Papdi & Sev Nimco",
    nameUrdu: "اسپائسی پاپڑی اور سیو نمکو",
    category: "nimco",
    categoryLabel: "Hyderi Nimco",
    categoryLabelUrdu: "حیدری نمکو",
    packQuantity: "500g",
    packQuantityUrdu: "۵۰۰ گرام",
    price: 380,
    rating: 4.8,
    reviewCount: 145,
    image: "/images/nimco_real.jpg",
    badge: "Extra Spicy",
    badgeUrdu: "پاپڑی سیو",
    description: "Crunchy flour crisps (papdi) and fine spiced gram flour noodles (sev).",
    descriptionUrdu: "چٹپٹی پاپڑی اور بیسن کے باریک سیو کا کلاسک امتزاج۔",
    isAvailable: true,
    featured: false
  }
];

const targetPath = path.join(process.cwd(), 'server', 'data', 'products.json');
fs.writeFileSync(targetPath, JSON.stringify(products, null, 2), 'utf8');
console.log(`Saved ${products.length} brochure products to ${targetPath}`);
