import fs from 'fs';
import path from 'path';

const products = [
  // ================= 1. SAMOSA (13 ITEMS) =================
  {
    id: "samosa-1",
    name: "Chicken Vonton",
    nameUrdu: "چکن وانٹون",
    category: "samosa",
    categoryLabel: "SAMOSA",
    categoryLabelUrdu: "سموسہ",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 240,
    rating: 4.9,
    reviewCount: 94,
    image: "/images/wonton_crispy.jpg",
    badge: "Best Seller",
    badgeUrdu: "سب سے مقبول",
    description: "Crispy fried wonton wrappers stuffed with seasoned minced chicken and herbs.",
    descriptionUrdu: "کرسپی گولڈن فرائیڈ وانٹون جس میں مصالحہ دار چکن کی بھرائی ہے۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "samosa-2",
    name: "Aaloo One Bite Samosa",
    nameUrdu: "آلو ون بائٹ سموسہ",
    category: "samosa",
    categoryLabel: "SAMOSA",
    categoryLabelUrdu: "سموسہ",
    packQuantity: "24 pcs",
    packQuantityUrdu: "۲۴ عدد",
    price: 350,
    rating: 4.8,
    reviewCount: 112,
    image: "/images/samosa_onebite.jpg",
    badge: "Tea Time Fav",
    badgeUrdu: "چائے کا ساتھی",
    description: "Mini bite-sized crispy samosas filled with authentic spiced potato.",
    descriptionUrdu: "چھوٹے سائز کے کرسپی سموسے، چٹپٹے آلو کے مصالحے کے ساتھ۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "samosa-3",
    name: "Chicken One Bite Samosa",
    nameUrdu: "چکن ون بائٹ سموسہ",
    category: "samosa",
    categoryLabel: "SAMOSA",
    categoryLabelUrdu: "سموسہ",
    packQuantity: "24 pcs",
    packQuantityUrdu: "۲۴ عدد",
    price: 400,
    rating: 4.9,
    reviewCount: 160,
    image: "/images/samosa_onebite.jpg",
    badge: "Top Rated",
    badgeUrdu: "ٹاپ ریٹڈ",
    description: "Bite-sized golden pastry filled with juicy shredded chicken.",
    descriptionUrdu: "شاندار چھوٹے چکن سموسے، لذیذ اور رسیلے چکن سے بھرپور۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "samosa-4",
    name: "Chicken Cheese Crispy One Bite Samosa",
    nameUrdu: "چکن چیز کرسپی ون بائٹ سموسہ",
    category: "samosa",
    categoryLabel: "SAMOSA",
    categoryLabelUrdu: "سموسہ",
    packQuantity: "24 pcs",
    packQuantityUrdu: "۲۴ عدد",
    price: 500,
    rating: 5.0,
    reviewCount: 210,
    image: "/images/samosa_onebite.jpg",
    badge: "Cheesy Treat",
    badgeUrdu: "چیزی اسپیشل",
    description: "Burst of melted mozzarella cheese and chicken in mini samosas.",
    descriptionUrdu: "پگھلتی ہوئی چیز اور چکن سے بھرپور کرسپی ون بائٹ سموسہ۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "samosa-5",
    name: "Chicken Cone Samosa",
    nameUrdu: "چکن کون سموسہ",
    category: "samosa",
    categoryLabel: "SAMOSA",
    categoryLabelUrdu: "سموسہ",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 350,
    rating: 4.7,
    reviewCount: 65,
    image: "/images/samosa_classic.jpg",
    badge: "Special Cone",
    badgeUrdu: "کون شیپ",
    description: "Unique crunchy cone-shaped pastry loaded with spicy chicken filling.",
    descriptionUrdu: "منفرد کون کی شکل میں بنا کرسپی چکن سموسہ۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "samosa-6",
    name: "Chicken Malai Boti Samosa",
    nameUrdu: "چکن ملائی بوٹی سموسہ",
    category: "samosa",
    categoryLabel: "SAMOSA",
    categoryLabelUrdu: "سموسہ",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 500,
    rating: 4.9,
    reviewCount: 140,
    image: "/images/samosa_classic.jpg",
    badge: "Creamy Melt",
    badgeUrdu: "ملائی بوٹی",
    description: "Tender chicken cooked in rich cream and mild herbs in crispy wrapper.",
    descriptionUrdu: "کریمی ملائی اور ہلکے مسالوں میں پکا چکن سموسہ۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "samosa-7",
    name: "Chicken Bar B Q Samosa",
    nameUrdu: "چکن بار بی کیو سموسہ",
    category: "samosa",
    categoryLabel: "SAMOSA",
    categoryLabelUrdu: "سموسہ",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 500,
    rating: 4.8,
    reviewCount: 125,
    image: "/images/samosa_classic.jpg",
    badge: "Smoky BBQ",
    badgeUrdu: "بار بی کیو",
    description: "Authentic charcoal-smoked BBQ spiced chicken chunks samosa.",
    descriptionUrdu: "کوئلے کے دھوئیں کا اصلی اسموکی ذائقہ چکن سموسہ۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "samosa-8",
    name: "Chicken Pizza Samosa",
    nameUrdu: "چکن پیزا سموسہ",
    category: "samosa",
    categoryLabel: "SAMOSA",
    categoryLabelUrdu: "سموسہ",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 550,
    rating: 4.9,
    reviewCount: 175,
    image: "/images/samosa_classic.jpg",
    badge: "Italian Fusion",
    badgeUrdu: "پیزا فلیور",
    description: "Pizza sauce, mozzarella cheese, capsicum, olives and chicken.",
    descriptionUrdu: "پیزا ساس، شملہ مرچ، زیتون، چیز اور چکن سموسہ۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "samosa-9",
    name: "Chicken Cheese Crispy Samosa",
    nameUrdu: "چکن چیز کرسپی سموسہ",
    category: "samosa",
    categoryLabel: "SAMOSA",
    categoryLabelUrdu: "سموسہ",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 400,
    rating: 4.8,
    reviewCount: 130,
    image: "/images/samosa_classic.jpg",
    badge: "Extra Cheesy",
    badgeUrdu: "چیزی کرسپی",
    description: "Cheese blend with shredded chicken in crunchy triangular crust.",
    descriptionUrdu: "خالص پنیر اور چکن کی لذیذ بھروائی والا خستہ سموسہ۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "samosa-10",
    name: "Chicken Chinese Samosa",
    nameUrdu: "چکن چائنیز سموسہ",
    category: "samosa",
    categoryLabel: "SAMOSA",
    categoryLabelUrdu: "سموسہ",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 350,
    rating: 4.7,
    reviewCount: 92,
    image: "/images/samosa_classic.jpg",
    badge: "Chowmein Style",
    badgeUrdu: "چائنیز",
    description: "Stir-fried vegetables, soy sauce, black pepper and chicken.",
    descriptionUrdu: "چائنیز سبزیاں، چکن اور کالی مرچ و سویا ساس کے ساتھ۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "samosa-11",
    name: "Qeema Samosa",
    nameUrdu: "قیمہ سموسہ",
    category: "samosa",
    categoryLabel: "SAMOSA",
    categoryLabelUrdu: "سموسہ",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 350,
    rating: 4.9,
    reviewCount: 180,
    image: "/images/samosa_classic.jpg",
    badge: "Traditional",
    badgeUrdu: "روایتی قیمہ",
    description: "Finely minced beef seasoned with onion, mint and garam masala.",
    descriptionUrdu: "خالص قیمہ، پودینہ اور ہری مرچوں سے سجا روایتی سموسہ۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "samosa-12",
    name: "Aaloo Samosa",
    nameUrdu: "آلو سموسہ",
    category: "samosa",
    categoryLabel: "SAMOSA",
    categoryLabelUrdu: "سموسہ",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 300,
    rating: 4.7,
    reviewCount: 88,
    image: "/images/samosa_classic.jpg",
    badge: "Classic",
    badgeUrdu: "کلاسک آلو",
    description: "Classic potato samosa with whole coriander and cumin spices.",
    descriptionUrdu: "ثابت دھنیا اور زیرہ کے مصالحے دار آلو والا سموسہ۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "samosa-13",
    name: "Daal Samosa",
    nameUrdu: "دال سموسہ",
    category: "samosa",
    categoryLabel: "SAMOSA",
    categoryLabelUrdu: "سموسہ",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 300,
    rating: 4.6,
    reviewCount: 74,
    image: "/images/samosa_classic.jpg",
    badge: "Crunchy Daal",
    badgeUrdu: "دال سموسہ",
    description: "Spiced split yellow lentil filling in extra crunchy pastry.",
    descriptionUrdu: "چٹپٹی دال کی بھروائی کے ساتھ خستہ اور لذیذ سموسہ۔",
    isAvailable: true,
    featured: false
  },

  // ================= 2. ROLL (13 ITEMS) =================
  {
    id: "roll-1",
    name: "Chicken One Bite Roll",
    nameUrdu: "چکن ون بائٹ رول",
    category: "roll",
    categoryLabel: "ROLL",
    categoryLabelUrdu: "رول",
    packQuantity: "24 pcs",
    packQuantityUrdu: "۲۴ عدد",
    price: 500,
    rating: 4.9,
    reviewCount: 155,
    image: "/images/spring_roll_crispy.jpg",
    badge: "Party Hit",
    badgeUrdu: "پارٹی ہٹ",
    description: "Crispy miniature spring rolls packed with seasoned chicken.",
    descriptionUrdu: "چھوٹے سائز کے کرسپی اسپرنگ رولز، چکن اور سبزیوں سے بھرپور۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "roll-2",
    name: "Chicken Cheese Crispy One Bite Roll",
    nameUrdu: "چکن چیز کرسپی ون بائٹ رول",
    category: "roll",
    categoryLabel: "ROLL",
    categoryLabelUrdu: "رول",
    packQuantity: "24 pcs",
    packQuantityUrdu: "۲۴ عدد",
    price: 550,
    rating: 5.0,
    reviewCount: 190,
    image: "/images/spring_roll_crispy.jpg",
    badge: "Cheesy Bite",
    badgeUrdu: "چیزی ون بائٹ",
    description: "Extra crunchy mini rolls with premium cheese and chicken.",
    descriptionUrdu: "چیڈر اور موزریلا چیز کے ساتھ کرسپی ون بائٹ چکن رولز۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "roll-3",
    name: "Chicken Bar B Q Roll",
    nameUrdu: "چکن بار بی کیو رول",
    category: "roll",
    categoryLabel: "ROLL",
    categoryLabelUrdu: "رول",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 500,
    rating: 4.8,
    reviewCount: 110,
    image: "/images/spring_roll_golden.jpg",
    badge: "Smoky Taste",
    badgeUrdu: "بار بی کیو",
    description: "Smoky charcoal BBQ chicken wrapped in crisp pastry rolls.",
    descriptionUrdu: "بار بی کیو کے اسموکی ذائقے دار چکن سے بھرے اسپرنگ رولز۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "roll-4",
    name: "Chicken Malai Boti Roll",
    nameUrdu: "چکن ملائی بوٹی رول",
    category: "roll",
    categoryLabel: "ROLL",
    categoryLabelUrdu: "رول",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 500,
    rating: 4.9,
    reviewCount: 165,
    image: "/images/spring_roll_golden.jpg",
    badge: "Creamy Malai",
    badgeUrdu: "ملائی بوٹی",
    description: "Rich creamy marinated chicken filling inside a golden crispy roll.",
    descriptionUrdu: "ملائی بوٹی کے رسیلے چکن سے سجے خاص رولز۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "roll-5",
    name: "Chicken Malai Boti One Bite Roll",
    nameUrdu: "چکن ملائی بوٹی ون بائٹ رول",
    category: "roll",
    categoryLabel: "ROLL",
    categoryLabelUrdu: "رول",
    packQuantity: "24 pcs",
    packQuantityUrdu: "۲۴ عدد",
    price: 500,
    rating: 4.9,
    reviewCount: 135,
    image: "/images/spring_roll_crispy.jpg",
    badge: "Mini Malai",
    badgeUrdu: "ون بائٹ ملائی",
    description: "Bite-sized creamy chicken malai boti rolls for tea time.",
    descriptionUrdu: "چھوٹے ون بائٹ رولز، ملائی بوٹی کے نرم ذائقے کے ساتھ۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "roll-6",
    name: "Chicken Pizza Roll",
    nameUrdu: "چکن پیزا رول",
    category: "roll",
    categoryLabel: "ROLL",
    categoryLabelUrdu: "رول",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 550,
    rating: 4.9,
    reviewCount: 145,
    image: "/images/spring_roll_golden.jpg",
    badge: "Pizza Flavor",
    badgeUrdu: "پیزا فلیور",
    description: "Pizza-sauce, oregano, melted cheese, and capsicum in crispy roll.",
    descriptionUrdu: "پیزا ساس، شملہ مرچ، زیتون اور چیز کا لذیذ چکن رول۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "roll-7",
    name: "Chicken Mayo Garlic Roll",
    nameUrdu: "چکن مایو گارلک رول",
    category: "roll",
    categoryLabel: "ROLL",
    categoryLabelUrdu: "رول",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 500,
    rating: 4.8,
    reviewCount: 120,
    image: "/images/spring_roll_golden.jpg",
    badge: "Garlic Mayo",
    badgeUrdu: "مایو گارلک",
    description: "Creamy garlic mayonnaise tossed with tender chicken chunks.",
    descriptionUrdu: "مایو گارلک ساس اور چکن سے بھرا کرسپی رول۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "roll-8",
    name: "Chicken Cheese Crispy Roll",
    nameUrdu: "چکن چیز کرسپی رول",
    category: "roll",
    categoryLabel: "ROLL",
    categoryLabelUrdu: "رول",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 400,
    rating: 4.8,
    reviewCount: 105,
    image: "/images/spring_roll_golden.jpg",
    badge: "Cheesy",
    badgeUrdu: "چیز کرسپی",
    description: "Golden crispy roll with melting mozzarella and chicken.",
    descriptionUrdu: "موزریلا پنیر اور چکن کی خستہ اور لذیذ جوڑی۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "roll-9",
    name: "Chicken Shahi Roll",
    nameUrdu: "چکن شاہی رول",
    category: "roll",
    categoryLabel: "ROLL",
    categoryLabelUrdu: "رول",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 350,
    rating: 4.7,
    reviewCount: 95,
    image: "/images/spring_roll_golden.jpg",
    badge: "Royal Taste",
    badgeUrdu: "شاہی ذائقہ",
    description: "Royal recipe with delicately spiced chicken and aromatics.",
    descriptionUrdu: "خاص شاہی مصالحوں اور چکن سے تیار کردہ رول۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "roll-10",
    name: "Chicken Mint Roll",
    nameUrdu: "چکن منٹ رول",
    category: "roll",
    categoryLabel: "ROLL",
    categoryLabelUrdu: "رول",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 350,
    rating: 4.7,
    reviewCount: 88,
    image: "/images/spring_roll_golden.jpg",
    badge: "Fresh Mint",
    badgeUrdu: "پودینہ فلیور",
    description: "Fresh garden mint and green herb chicken filling inside roll.",
    descriptionUrdu: "تازہ پودینے اور ہری چٹنی کے امتزاج سے تیار چکن رول۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "roll-11",
    name: "Chicken Chinese Roll",
    nameUrdu: "چکن چائنیز رول",
    category: "roll",
    categoryLabel: "ROLL",
    categoryLabelUrdu: "رول",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 350,
    rating: 4.7,
    reviewCount: 82,
    image: "/images/spring_roll_golden.jpg",
    badge: "Chinese Style",
    badgeUrdu: "چائنیز",
    description: "Shredded chicken and julienne vegetables with soy sauce.",
    descriptionUrdu: "چکن اور سبزیوں کے ساتھ کلاسک چائنیز رول۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "roll-12",
    name: "Chicken Bread Roll",
    nameUrdu: "چکن بریڈ رول",
    category: "roll",
    categoryLabel: "ROLL",
    categoryLabelUrdu: "رول",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 300,
    rating: 4.8,
    reviewCount: 78,
    image: "/images/spring_roll_golden.jpg",
    badge: "Bread Coated",
    badgeUrdu: "بریڈ رول",
    description: "Soft bread rolled around chicken coated in crispy crumbs.",
    descriptionUrdu: "بریڈ کرمبز کی کوٹنگ میں خستہ چکن بریڈ رول۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "roll-13",
    name: "Chicken Chimmy Changa",
    nameUrdu: "چکن چمی چانگا",
    category: "roll",
    categoryLabel: "ROLL",
    categoryLabelUrdu: "رول",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 350,
    rating: 4.8,
    reviewCount: 90,
    image: "/images/spring_roll_golden.jpg",
    badge: "Mexican Style",
    badgeUrdu: "چمی چانگا",
    description: "Deep-fried stuffed pocket loaded with spicy chicken and salsa.",
    descriptionUrdu: "میکسیکن ذائقے کی چکن پاکٹ، تلی ہوئی اور مسالے دار۔",
    isAvailable: true,
    featured: false
  },

  // ================= 3. KABAB (11 ITEMS) =================
  {
    id: "kabab-1",
    name: "Chicken Shami Kabab",
    nameUrdu: "چکن شامی کباب",
    category: "kabab",
    categoryLabel: "KABAB",
    categoryLabelUrdu: "کباب",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 600,
    rating: 4.9,
    reviewCount: 220,
    image: "/images/shami_kabab_real.jpg",
    badge: "Best Seller",
    badgeUrdu: "سب سے مقبول",
    description: "Chicken and split yellow gram patties with fragrant spices.",
    descriptionUrdu: "چکن اور چنے کی دال کے اصلی ریشے دار شامی کباب۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "kabab-2",
    name: "Beef Shami Kabab",
    nameUrdu: "بیف شامی کباب",
    category: "kabab",
    categoryLabel: "KABAB",
    categoryLabelUrdu: "کباب",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 600,
    rating: 5.0,
    reviewCount: 245,
    image: "/images/shami_kabab_real.jpg",
    badge: "Authentic Beef",
    badgeUrdu: "خالص بیف",
    description: "Traditional Karachi beef shami kababs with tender shredded beef.",
    descriptionUrdu: "خالص گوشت سے بنے ہوئے لذیذ اور ریشمی شامی کباب۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "kabab-3",
    name: "Chicken Seekh Kabab",
    nameUrdu: "چکن سیخ کباب",
    category: "kabab",
    categoryLabel: "KABAB",
    categoryLabelUrdu: "کباب",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 650,
    rating: 4.9,
    reviewCount: 185,
    image: "/images/seekh_kabab_real.jpg",
    badge: "Charcoal BBQ",
    badgeUrdu: "سیخ کباب",
    description: "Minced chicken seasoned with coriander, cumin and BBQ smoke.",
    descriptionUrdu: "خوشبودار مصالحوں اور کوئلے کی خوشبو والے چکن سیخ کباب۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "kabab-4",
    name: "Chicken Chapli Kabab",
    nameUrdu: "چکن چپلی کباب",
    category: "kabab",
    categoryLabel: "KABAB",
    categoryLabelUrdu: "کباب",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 500,
    rating: 4.8,
    reviewCount: 140,
    image: "/images/chapli_kabab_real.jpg",
    badge: "Peshawari",
    badgeUrdu: "چپلی کباب",
    description: "Peshawari style chicken patty with crushed pomegranate and tomato.",
    descriptionUrdu: "اناردانہ اور ٹماٹر کے چٹپٹے مسالوں والے چکن چپلی کباب۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "kabab-5",
    name: "Beef Chapli Kabab",
    nameUrdu: "بیف چپلی کباب",
    category: "kabab",
    categoryLabel: "KABAB",
    categoryLabelUrdu: "کباب",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 500,
    rating: 4.9,
    reviewCount: 160,
    image: "/images/chapli_kabab_real.jpg",
    badge: "Special Beef",
    badgeUrdu: "بیف چپلی",
    description: "Traditional spiced beef patty infused with chili flakes and mint.",
    descriptionUrdu: "اصلی پشاوری بیف چپلی کباب، چٹپٹا اور رسیلا۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "kabab-6",
    name: "Chicken Burger Patty",
    nameUrdu: "چکن برگر پیٹی",
    category: "kabab",
    categoryLabel: "KABAB",
    categoryLabelUrdu: "کباب",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 400,
    rating: 4.7,
    reviewCount: 98,
    image: "/images/shami_kabab_real.jpg",
    badge: "Burger Ready",
    badgeUrdu: "برگر پیٹی",
    description: "Juicy chicken burger patties ready for homemade burgers.",
    descriptionUrdu: "گھر کے مزیدار برگرز کے لیے تیار رسیلی چکن پیٹی۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "kabab-7",
    name: "Chicken Cutless",
    nameUrdu: "چکن کٹلس",
    category: "kabab",
    categoryLabel: "KABAB",
    categoryLabelUrdu: "کباب",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 500,
    rating: 4.8,
    reviewCount: 115,
    image: "/images/shami_kabab_real.jpg",
    badge: "Potato & Chicken",
    badgeUrdu: "کٹلس",
    description: "Crumb coated mashed potato and chicken patties with green chilies.",
    descriptionUrdu: "آلو اور چکن کے مصالحہ دار مکسچر سے بنے کٹلس۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "kabab-8",
    name: "Chicken Stick",
    nameUrdu: "چکن اسٹک",
    category: "kabab",
    categoryLabel: "KABAB",
    categoryLabelUrdu: "کباب",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 550,
    rating: 4.8,
    reviewCount: 102,
    image: "/images/seekh_kabab_real.jpg",
    badge: "Skewers",
    badgeUrdu: "اسٹک",
    description: "Marinated juicy chicken chunks on skewers ready to fry.",
    descriptionUrdu: "سیخ پر لگے مسالے دار چکن پیسز، فرائی کے لیے تیار۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "kabab-9",
    name: "Chicken Kofta",
    nameUrdu: "چکن کوفتہ",
    category: "kabab",
    categoryLabel: "KABAB",
    categoryLabelUrdu: "کباب",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 500,
    rating: 4.7,
    reviewCount: 88,
    image: "/images/shami_kabab_real.jpg",
    badge: "Meatballs",
    badgeUrdu: "کوفتے",
    description: "Succulent chicken meatballs blended with aromatic herbs.",
    descriptionUrdu: "سالن یا فرائی کے لیے تیار نرم اور رسیلے چکن کوفتے۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "kabab-10",
    name: "Chicken Momos (Steamed)",
    nameUrdu: "چکن موموز (اسٹیمڈ)",
    category: "kabab",
    categoryLabel: "KABAB",
    categoryLabelUrdu: "کباب",
    packQuantity: "10 pcs",
    packQuantityUrdu: "۱۰ عدد",
    price: 400,
    rating: 4.9,
    reviewCount: 195,
    image: "/images/momos_steamed_real.jpg",
    badge: "Dumplings",
    badgeUrdu: "اسٹیمڈ موموز",
    description: "Delicate steamed dumplings with minced chicken and ginger.",
    descriptionUrdu: "بہت نرم اور رسیلے چکن دم پخت موموز (ڈمپلنگز)۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "kabab-11",
    name: "Chicken Momos (Fried)",
    nameUrdu: "چکن موموز (فرائیڈ)",
    category: "kabab",
    categoryLabel: "KABAB",
    categoryLabelUrdu: "کباب",
    packQuantity: "08 pcs",
    packQuantityUrdu: "۰۸ عدد",
    price: 400,
    rating: 4.9,
    reviewCount: 170,
    image: "/images/momos_fried_real.jpg",
    badge: "Crispy Momos",
    badgeUrdu: "فرائیڈ موموز",
    description: "Golden pan-fried crunchy momos stuffed with chicken.",
    descriptionUrdu: "کرسپی اور چٹپٹے تلے ہوئے چکن موموز۔",
    isAvailable: true,
    featured: true
  },

  // ================= 4. PIZZA (2 ITEMS) =================
  {
    id: "pizza-1",
    name: "B.B.Q Mini Pizza",
    nameUrdu: "بی بی کیو منی پیزا",
    category: "pizza",
    categoryLabel: "PIZZA",
    categoryLabelUrdu: "پیزا",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 450,
    rating: 4.9,
    reviewCount: 160,
    image: "/images/mini_pizza_real.jpg",
    badge: "BBQ Pizza",
    badgeUrdu: "بار بی کیو پیزا",
    description: "Fluffy pizza dough with BBQ chicken, sauce and mozzarella cheese.",
    descriptionUrdu: "بار بی کیو چکن اور موزریلا چیز والا منی پیزا (۶ عدد)۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "pizza-2",
    name: "Malai Boti Mini Pizza",
    nameUrdu: "ملائی بوٹی منی پیزا",
    category: "pizza",
    categoryLabel: "PIZZA",
    categoryLabelUrdu: "پیزا",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 500,
    rating: 5.0,
    reviewCount: 185,
    image: "/images/mini_pizza_real.jpg",
    badge: "Creamy Pizza",
    badgeUrdu: "ملائی بوٹی پیزا",
    description: "Creamy malai chicken boti topping with rich melted cheese.",
    descriptionUrdu: "ملائی بوٹی چکن اور کریمی چیز والا اسپیشل منی پیزا (۶ عدد)۔",
    isAvailable: true,
    featured: true
  },

  // ================= 5. OTHER SPECIAL (15 ITEMS) =================
  {
    id: "special-1",
    name: "Hot Shot",
    nameUrdu: "ہاٹ شاٹس",
    category: "special",
    categoryLabel: "OTHER SPECIAL",
    categoryLabelUrdu: "دیگر اسپیشل",
    packQuantity: "250gm - 06 pcs",
    packQuantityUrdu: "۲۵۰ گرام (۰۶ عدد)",
    price: 450,
    rating: 4.8,
    reviewCount: 130,
    image: "/images/nuggets_real.jpg",
    badge: "Spicy Crunch",
    badgeUrdu: "ہاٹ شاٹس",
    description: "Spicy battered bite-sized whole chicken breast chunks.",
    descriptionUrdu: "اسپائسی کرسپی چکن بائٹس (۲۵۰ گرام - ۰۶ عدد)۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "special-2",
    name: "Chicken Nuggets Big",
    nameUrdu: "چکن نگٹس (بڑا پیک)",
    category: "special",
    categoryLabel: "OTHER SPECIAL",
    categoryLabelUrdu: "دیگر اسپیشل",
    packQuantity: "24 pcs",
    packQuantityUrdu: "۲۴ عدد",
    price: 550,
    rating: 4.9,
    reviewCount: 215,
    image: "/images/nuggets_real.jpg",
    badge: "Family Pack",
    badgeUrdu: "فیملی پیک",
    description: "Crumbed pure chicken breast nuggets, family pack 24 pieces.",
    descriptionUrdu: "خالص چکن بریسٹ سے بنے نگٹس فیملی پیک (۲۴ عدد)۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "special-3",
    name: "Chicken Nuggets Small",
    nameUrdu: "چکن نگٹس (چھوٹا پیک)",
    category: "special",
    categoryLabel: "OTHER SPECIAL",
    categoryLabelUrdu: "دیگر اسپیشل",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 300,
    rating: 4.8,
    reviewCount: 140,
    image: "/images/nuggets_real.jpg",
    badge: "Kids Favorite",
    badgeUrdu: "نگٹس",
    description: "Crispy chicken nuggets 12 pieces small pack.",
    descriptionUrdu: "خالص چکن کے ۱۲ عدد نگٹس کا پیک۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "special-4",
    name: "Chicken Cheese Ball",
    nameUrdu: "چکن چیز بولز",
    category: "special",
    categoryLabel: "OTHER SPECIAL",
    categoryLabelUrdu: "دیگر اسپیشل",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 500,
    rating: 4.9,
    reviewCount: 175,
    image: "/images/nuggets_real.jpg",
    badge: "Cheese Burst",
    badgeUrdu: "چیز بولز",
    description: "Crispy spheres packed with gooey cheese and chicken.",
    descriptionUrdu: "پگھلتی چیز اور چکن کے گولڈن فرائیڈ بولز (۱۲ عدد)۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "special-5",
    name: "Chicken Cheese Lolypop",
    nameUrdu: "چکن چیز لولی پاپ",
    category: "special",
    categoryLabel: "OTHER SPECIAL",
    categoryLabelUrdu: "دیگر اسپیشل",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 350,
    rating: 4.8,
    reviewCount: 110,
    image: "/images/nuggets_real.jpg",
    badge: "Fun Treat",
    badgeUrdu: "لولی پاپ",
    description: "Chicken lollipop drumsticks stuffed with mozzarella cheese.",
    descriptionUrdu: "چیز سے بھرے خستہ چکن لولی پاپس (۰۶ عدد)۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "special-6",
    name: "Chicken Donuts",
    nameUrdu: "چکن ڈونٹس",
    category: "special",
    categoryLabel: "OTHER SPECIAL",
    categoryLabelUrdu: "دیگر اسپیشل",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 500,
    rating: 4.8,
    reviewCount: 155,
    image: "/images/nuggets_real.jpg",
    badge: "Unique",
    badgeUrdu: "ڈونٹس",
    description: "Savory ring-shaped chicken patties coated in breadcrumbs.",
    descriptionUrdu: "ڈونٹ شیپ میں بنے ہوئے کرسپی چکن پیٹیز (۱۲ عدد)۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "special-7",
    name: "Chicken Finger",
    nameUrdu: "چکن فنگرز",
    category: "special",
    categoryLabel: "OTHER SPECIAL",
    categoryLabelUrdu: "دیگر اسپیشل",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 400,
    rating: 4.7,
    reviewCount: 95,
    image: "/images/nuggets_real.jpg",
    badge: "Crispy Strips",
    badgeUrdu: "فنگرز",
    description: "Tender chicken strips in crunchy breading 12 pieces.",
    descriptionUrdu: "چکن اسٹرپس کرسپی کوٹنگ کے ساتھ (۱۲ عدد)۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "special-8",
    name: "Chicken Popcorn",
    nameUrdu: "چکن پاپ کارن",
    category: "special",
    categoryLabel: "OTHER SPECIAL",
    categoryLabelUrdu: "دیگر اسپیشل",
    packQuantity: "30 pcs",
    packQuantityUrdu: "۳۰ عدد",
    price: 350,
    rating: 4.8,
    reviewCount: 135,
    image: "/images/nuggets_real.jpg",
    badge: "Movie Snack",
    badgeUrdu: "پاپ کارن",
    description: "Bite-sized crunchy spiced popcorn chicken 30 pieces.",
    descriptionUrdu: "کرسپی چکن پاپ کارن بائٹس (۳۰ عدد)۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "special-9",
    name: "Chicken Chillos",
    nameUrdu: "چکن چیلووز",
    category: "special",
    categoryLabel: "OTHER SPECIAL",
    categoryLabelUrdu: "دیگر اسپیشل",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 350,
    rating: 4.7,
    reviewCount: 80,
    image: "/images/nuggets_real.jpg",
    badge: "Spicy Bites",
    badgeUrdu: "چیلووز",
    description: "Green chili and chicken stuffed crispy patties 6 pieces.",
    descriptionUrdu: "ہری مرچ اور چکن سے بنے اسپیشل چیلووز (۰۶ عدد)۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "special-10",
    name: "Chicken Pizza Puff",
    nameUrdu: "چکن پیزا پف",
    category: "special",
    categoryLabel: "OTHER SPECIAL",
    categoryLabelUrdu: "دیگر اسپیشل",
    packQuantity: "12 pcs",
    packQuantityUrdu: "۱۲ عدد",
    price: 450,
    rating: 4.8,
    reviewCount: 120,
    image: "/images/mini_pizza_real.jpg",
    badge: "Flaky Puff",
    badgeUrdu: "پیزا پف",
    description: "Flaky puff pastry stuffed with pizza sauce, cheese and chicken.",
    descriptionUrdu: "پف پیسٹری میں بند پیزا ساس اور چکن چیز (۱۲ عدد)۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "special-11",
    name: "French Fries",
    nameUrdu: "فرینچ فرائز",
    category: "special",
    categoryLabel: "OTHER SPECIAL",
    categoryLabelUrdu: "دیگر اسپیشل",
    packQuantity: "450gm",
    packQuantityUrdu: "۴۵۰ گرام",
    price: 250,
    rating: 4.7,
    reviewCount: 110,
    image: "/images/french_fries_real.jpg",
    badge: "Crispy Potato",
    badgeUrdu: "فرائز",
    description: "Straight cut crispy potato fries pack 450 grams.",
    descriptionUrdu: "تازہ اور خستہ کٹ پوٹیٹو فرائز (۴۵۰ گرام)۔",
    isAvailable: true,
    featured: false
  },
  {
    id: "special-12",
    name: "Roll Patti",
    nameUrdu: "رول پٹی",
    category: "special",
    categoryLabel: "OTHER SPECIAL",
    categoryLabelUrdu: "دیگر اسپیشل",
    packQuantity: "1 kg",
    packQuantityUrdu: "۱ کلو",
    price: 320,
    rating: 4.9,
    reviewCount: 190,
    image: "/images/paratha_real.jpg",
    badge: "100% Fresh",
    badgeUrdu: "تازہ پٹی",
    description: "Freshly prepared thin spring roll sheets 1 kg pack.",
    descriptionUrdu: "گھر پر رول بنانے کے لیے تازہ اور باریک رول پٹی (۱ کلو)۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "special-13",
    name: "Samosa Patti",
    nameUrdu: "سموسہ پٹی",
    category: "special",
    categoryLabel: "OTHER SPECIAL",
    categoryLabelUrdu: "دیگر اسپیشل",
    packQuantity: "1 kg",
    packQuantityUrdu: "۱ کلو",
    price: 320,
    rating: 4.9,
    reviewCount: 205,
    image: "/images/paratha_real.jpg",
    badge: "100% Fresh",
    badgeUrdu: "سموسہ پٹی",
    description: "Traditional thin samosa pastry sheets 1 kg pack.",
    descriptionUrdu: "خستہ سموسوں کے لیے مشہور حیدری سموسہ پٹی (۱ کلو)۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "special-14",
    name: "Lachha Paratha",
    nameUrdu: "لچھا پراٹھا",
    category: "special",
    categoryLabel: "OTHER SPECIAL",
    categoryLabelUrdu: "دیگر اسپیشل",
    packQuantity: "06 pcs",
    packQuantityUrdu: "۰۶ عدد",
    price: 220,
    rating: 4.9,
    reviewCount: 180,
    image: "/images/paratha_real.jpg",
    badge: "Multi-Layered",
    badgeUrdu: "لچھا پراٹھا",
    description: "Multi-layered crispy flaky parathas ready on tawa 6 pieces.",
    descriptionUrdu: "پرت دار خستہ لچھا پراٹھا، صرف ۲ منٹ میں تیار (۰۶ عدد)۔",
    isAvailable: true,
    featured: true
  },
  {
    id: "special-15",
    name: "Plain Puri",
    nameUrdu: "پلین پوری",
    category: "special",
    categoryLabel: "OTHER SPECIAL",
    categoryLabelUrdu: "دیگر اسپیشل",
    packQuantity: "10 pcs",
    packQuantityUrdu: "۱۰ عدد",
    price: 220,
    rating: 4.8,
    reviewCount: 130,
    image: "/images/paratha_real.jpg",
    badge: "Soft & Fluffy",
    badgeUrdu: "پوری",
    description: "Soft, puffy, breakfast puris 10 pieces pack.",
    descriptionUrdu: "ناشتے کے لیے نرم اور پھولی ہوئی روایتی پوریاں (۱۰ عدد)۔",
    isAvailable: true,
    featured: false
  }
];

const targetPath = path.join(process.cwd(), 'server', 'data', 'products.json');
fs.writeFileSync(targetPath, JSON.stringify(products, null, 2), 'utf8');
console.log(`Saved EXACT ${products.length} brochure products (54 items, 0 extra) to ${targetPath}`);
